### ISSUE TITLE
Connecting to RETS 1.7

### ISSUE THREAD

**Issue by thezenmonkey** [troydavisson/PHRETS#10]
I'm having trouble using the example Download CSV script on a 1.7 server. It connects but finds 0 records no matter what the date is

**Comment by alexsmartens** [comment]
Hi there,
I'm also having a problem with `idx_dt`.  My quires by `timestamp_sql` work fine however the queries by `idx_dt` just don't. Any suggestions?

### Query Examples

- `query="(timestamp_sql=2020-09-09T00:00:00+)"` works just fine;
- `query="(idx_dt=2010-09-09T00:00:00+)"` returns with `ReplyCode="20202" ReplyText="Invalid Select: The Select statement contains field names that are not recognized by the server.`

### Data types
I checked with retsmd.com, both data types are the same:
![RETS M D  ScreenShoot](https://user-images.githubusercontent.com/26261714/92942739-db61ba80-f41f-11ea-8f55-b947328bbd96.png)
The `timestamp_sql` and `idx_dt` values also look the same in the data.
