### ISSUE TITLE
Default Schema

### ISSUE THREAD

**Issue by jmancusi** [troydavisson/PHRETS#100]
I think it would be really useful if the project had a default schema with it. This would allow for some development prior to having access to a RETS server. Even if the particular schema was just an example and wouldn't match your RETS server exactly it would be really helpful to allow the developer to wrap their head around the data.

Thanks!

**Comment by menriquez** [comment]
Sure this seems reasonable...

Here is one for the Greater Las Vegas RETS system...but be aware that every single RETS system across the country has a different schema.

CREATE TABLE `glvar_property_16` (
  `sysid_sysid` int(11) DEFAULT NULL,
  `Property_Type_1` varchar(52) DEFAULT NULL,
  `Legal_LctnTownship_(Search)_3` varchar(34) DEFAULT NULL,
  `Legal_Lctn_Range_(Search)_4` varchar(38) DEFAULT NULL,
  `Legal_Lctn_Section_(Search)_5` varchar(35) DEFAULT NULL,
  `Zip_Code_10` varchar(44) DEFAULT NULL,
  `StatusChangeDate_18` datetime DEFAULT NULL,
  `Actual_Close_Date_25` datetime DEFAULT NULL,
  `LA_Name_26` varchar(82) DEFAULT NULL,
  `Area_37` int(11) DEFAULT NULL,
  `Bedrooms_68` int(11) DEFAULT NULL,
  `Acceptance_Date_85` datetime DEFAULT NULL,
  `County_Name_87` varchar(42) DEFAULT NULL,
  `Compass_Point_100` varchar(33) DEFAULT NULL,
  `DOM_101` int(11) DEFAULT NULL,
  `Entry_Date_104` datetime DEFAULT NULL,
  `Images_129` int(11) DEFAULT NULL,
  `Last_Transaction_Code_134` varchar(34) DEFAULT NULL,
  `Last_Transaction_Date_135` datetime DEFAULT NULL,
  `List_Office_Code_137` varchar(44) DEFAULT NULL,
  `List_Date_138` datetime DEFAULT NULL,
  `List_Agent_Public_ID_143` varchar(47) DEFAULT NULL,
  `List_Price_144` decimal(14,2) DEFAULT NULL,
  `ML_#_163` varchar(42) DEFAULT NULL,
  `Original_List_Price_173` decimal(14,2) DEFAULT NULL,
  `Parcel_#_176` varchar(107) DEFAULT NULL,
  `Photo_Instructions_182` varchar(42) DEFAULT NULL,
  `Previous_Price_199` decimal(14,2) DEFAULT NULL,
  `Record_Delete_Date_205` datetime DEFAULT NULL,
  `Record_Delete_Flag_207` varchar(33) DEFAULT NULL,
  `Sale_Price_210` decimal(14,2) DEFAULT NULL,
  `Buyer_Broker_211` varchar(44) DEFAULT NULL,
  `Buyer_Agent_Public_ID_218` varchar(47) DEFAULT NULL,
  `Sold_Term_233` varchar(39) DEFAULT NULL,
  `Sort_Price_235` decimal(14,2) DEFAULT NULL,
  `Status_242` varchar(52) DEFAULT NULL,
  `Street_Name_243` varchar(82) DEFAULT NULL,
  `Street_Number_244` int(11) DEFAULT NULL,
  `Year_Built_264` int(11) DEFAULT NULL,
  `Subdivision_Number_1734` int(11) DEFAULT NULL,
  `Est_Clo/Lse_dt_1736` datetime DEFAULT NULL,
  `LP/SqFt_(w/cents)_1738` decimal(14,2) DEFAULT NULL,
  `IDX_1809` varchar(33) DEFAULT NULL,
  `Virtual_Tour_Link_2139` varchar(287) DEFAULT NULL,
  `Open_House_Flag_2237` decimal(14,2) DEFAULT NULL,
  `Last_Image_Trans_Date_2238` datetime DEFAULT NULL,
  `LP/SqFt_2341` decimal(14,2) DEFAULT NULL,
  `Metro_Map_Coor_XP_2343` varchar(34) DEFAULT NULL,
  `Metro_Map_Page_XP_2345` int(11) DEFAULT NULL,
  `Subdivision_Name_XP_2353` varchar(62) DEFAULT NULL,
  `SP/SqFt_[w/cents]_2359` decimal(14,2) DEFAULT NULL,
  `Approx_Liv_Area_2361` int(11) DEFAULT NULL,
  `Subdivision_#_(Search)_2367` varchar(37) DEFAULT NULL,
  `Short_Sale_2369` varchar(33) DEFAULT NULL,
  `Bedrooms_(Total_Possible_#)_2379` int(11) DEFAULT NULL,
  `Days_from_Listing_to_Close_2381` int(11) DEFAULT NULL,
  `Fax_#_2383` varchar(44) DEFAULT NULL,
  `Email_2385` varchar(72) DEFAULT NULL,
  `UnitNumber_2386` varchar(44) DEFAULT NULL,
  `Ownership_2505` varchar(35) DEFAULT NULL,
  `LADOM_2655` int(11) DEFAULT NULL,
  `Building_Number_2664` varchar(35) DEFAULT NULL,
  `Total_Floors_2665` varchar(35) DEFAULT NULL,
  `Elevator_Floor_#_2667` int(11) DEFAULT NULL,
  `Builder_2668` varchar(42) DEFAULT NULL,
  `Model_2669` varchar(42) DEFAULT NULL,
  `Built_Description_2670` varchar(48) DEFAULT NULL,
  `Location_2671` varchar(44) DEFAULT NULL,
  `Tower_Name_2672` varchar(67) DEFAULT NULL,
  `Age_Restricted_Community_2673` varchar(33) DEFAULT NULL,
  `Association_Features_Available_2677` varchar(464) DEFAULT NULL,
  `Elementary_School_3-5_2678` varchar(36) DEFAULT NULL,
  `Elementary_School_K-2_2679` varchar(36) DEFAULT NULL,
  `High_School_2680` varchar(36) DEFAULT NULL,
  `Jr_High_School_2681` varchar(36) DEFAULT NULL,
  `Year_Round_School_2682` varchar(33) DEFAULT NULL,
  `Metro_Map_Coor_2683` varchar(34) DEFAULT NULL,
  `Metro_Map__Page_2684` int(11) DEFAULT NULL,
  `Building_Description_2685` varchar(62) DEFAULT NULL,
  `Unit_Levels_2686` varchar(40) DEFAULT NULL,
  `Junior_Suite_(under_600_sqft)_2687` varchar(33) DEFAULT NULL,
  `Full_Baths_2688` int(11) DEFAULT NULL,
  `3/4_Baths_2689` int(11) DEFAULT NULL,
  `Baths_Total_2690` int(11) DEFAULT NULL,
  `Half_Baths_2691` int(11) DEFAULT NULL,
  `Unit_Description_2692` varchar(80) DEFAULT NULL,
  `Condo_Conversion_2693` varchar(33) DEFAULT NULL,
  `Approx_Liv_Area_2694` int(11) DEFAULT NULL,
  `#Den/Other_2695` int(11) DEFAULT NULL,
  `Private_Pool_2696` varchar(33) DEFAULT NULL,
  `Unit_Pool_Indoor_2697` varchar(33) DEFAULT NULL,
  `Private_Spa_2698` varchar(33) DEFAULT NULL,
  `Unit_Spa_Indoor_2699` varchar(33) DEFAULT NULL,
  `#_of_Loft_Areas_2700` int(11) DEFAULT NULL,
  `Parking_Description_2701` varchar(96) DEFAULT NULL,
  `#_of_Parking_Spaces_Included_2702` int(11) DEFAULT NULL,
  `Parking_Level_2703` varchar(35) DEFAULT NULL,
  `Parking_Space_ID_#_2704` varchar(47) DEFAULT NULL,
  `Directions_2705` varchar(202) DEFAULT NULL,
  `Living_Room_Description_2708` varchar(72) DEFAULT NULL,
  `Living_Room_Dimensions_2709` varchar(39) DEFAULT NULL,
  `Great_Room_Description_2710` varchar(72) DEFAULT NULL,
  `Great_Room_Dimensions_2711` varchar(39) DEFAULT NULL,
  `Dining_Room_Description_2714` varchar(56) DEFAULT NULL,
  `Dining_Room_Dimensions_2715` varchar(37) DEFAULT NULL,
  `Kitchen_Description_2716` varchar(140) DEFAULT NULL,
  `Kitchen_Flooring_2717` varchar(57) DEFAULT NULL,
  `Kitchen_Countertops_2718` varchar(57) DEFAULT NULL,
  `Master_Bedroom_Description_2719` varchar(128) DEFAULT NULL,
  `Master_Bedroom_Dimensions_2720` varchar(39) DEFAULT NULL,
  `Master_Bath_Description_2721` varchar(152) DEFAULT NULL,
  `2nd_Bedroom_Description_2722` varchar(80) DEFAULT NULL,
  `2nd_Bedroom_Dimensions_2723` varchar(37) DEFAULT NULL,
  `_3rd_Bedroom_Description_2724` varchar(80) DEFAULT NULL,
  `3rd_Bedroom_Dimensions_2725` varchar(37) DEFAULT NULL,
  `4th_Bedroom_Description_2726` varchar(80) DEFAULT NULL,
  `4th_Bedroom_Dimensions_2727` varchar(37) DEFAULT NULL,
  `5th_Bedroom_Description_2728` varchar(80) DEFAULT NULL,
  `5th_Bedroom_Dimensions_2729` varchar(37) DEFAULT NULL,
  `Den/Other_Dimensions_2730` varchar(37) DEFAULT NULL,
  `Loft_Area_Dimensions_2731` varchar(37) DEFAULT NULL,
  `Loft_Dimensions_1st_Floor_2732` varchar(39) DEFAULT NULL,
  `Loft_Dimensions_2nd_Floor_2733` varchar(39) DEFAULT NULL,
  `Loft_Description_2734` varchar(82) DEFAULT NULL,
  `Furnishings_Description_2735` varchar(48) DEFAULT NULL,
  `#_Terraces_2736` int(11) DEFAULT NULL,
  `Terrace_Total_Sqft_2737` int(11) DEFAULT NULL,
  `Terrace_Location_2738` varchar(56) DEFAULT NULL,
  `Refrigerator_Included_2739` varchar(33) DEFAULT NULL,
  `Refrigerator_Description_2740` varchar(52) DEFAULT NULL,
  `Disposal_Included_2741` varchar(33) DEFAULT NULL,
  `Washer_Included_2742` varchar(33) DEFAULT NULL,
  `Dryer_Included_2743` varchar(33) DEFAULT NULL,
  `Dryer_Utilities_2744` varchar(33) DEFAULT NULL,
  `Washer/Dryer_Location_2745` varchar(44) DEFAULT NULL,
  `Washer_Dryer_Description_2746` varchar(38) DEFAULT NULL,
  `Dishwasher_Included_2747` varchar(33) DEFAULT NULL,
  `Dishwasher_Description_2748` varchar(56) DEFAULT NULL,
  `Other_Appliances_2749` varchar(104) DEFAULT NULL,
  `Oven_Description_2750` varchar(80) DEFAULT NULL,
  `Interior_2751` varchar(92) DEFAULT NULL,
  `Flooring_2752` varchar(92) DEFAULT NULL,
  `Fireplace_2753` varchar(33) DEFAULT NULL,
  `Fireplace_Description_2754` varchar(64) DEFAULT NULL,
  `Fireplace_Location_2755` varchar(56) DEFAULT NULL,
  `Primary_View_Direction_2756` varchar(33) DEFAULT NULL,
  `Views_2757` varchar(67) DEFAULT NULL,
  `Exterior_Unit_Description_2758` varchar(104) DEFAULT NULL,
  `Home_Protection_Plan_2759` varchar(33) DEFAULT NULL,
  `Heating_Description_2760` varchar(60) DEFAULT NULL,
  `Heating_Fuel_2761` varchar(42) DEFAULT NULL,
  `Hot_Water_2762` varchar(40) DEFAULT NULL,
  `Cooling_Fuel_2763` varchar(36) DEFAULT NULL,
  `Cooling_System_2764` varchar(72) DEFAULT NULL,
  `Energy_Description_2765` varchar(64) DEFAULT NULL,
  `Utility_Information_2766` varchar(60) DEFAULT NULL,
  `Green_Building_Certification_2767` varchar(33) DEFAULT NULL,
  `Leed_Certified_2768` varchar(33) DEFAULT NULL,
  `#_Storage_Units_2769` int(11) DEFAULT NULL,
  `Storage_Unit_Desc_2770` varchar(38) DEFAULT NULL,
  `Storage_Unit_Dim_2771` varchar(37) DEFAULT NULL,
  `Storage_Secure_2773` varchar(33) DEFAULT NULL,
  `On_Site_Staff_2774` varchar(33) DEFAULT NULL,
  `On_Site_Staff_Includes_2775` varchar(132) DEFAULT NULL,
  `Services_Available_On_Site_2776` varchar(112) DEFAULT NULL,
  `Security_2777` varchar(122) DEFAULT NULL,
  `Association_Fee_Y/N_2778` varchar(33) DEFAULT NULL,
  `Association_Name_2779` varchar(52) DEFAULT NULL,
  `Association_Phone_2780` varchar(44) DEFAULT NULL,
  `Master_Plan_Fee_-_M,Q,Y,N_2781` varchar(33) DEFAULT NULL,
  `Master_Plan_Fee_Amount_2782` int(11) DEFAULT NULL,
  `Association_Fee_1_2783` int(11) DEFAULT NULL,
  `Association_Fee_1_-_M,Q,Y,N_2784` varchar(33) DEFAULT NULL,
  `Association_Fee_2_2785` int(11) DEFAULT NULL,
  `Association_Fee_2_-_M,Q,Y,N_2786` varchar(33) DEFAULT NULL,
  `Assoc_Fee_Includes_2787` varchar(112) DEFAULT NULL,
  `HOA_Minimum_Rental_Cycle_2788` varchar(40) DEFAULT NULL,
  `Pets_Allowed_2789` varchar(33) DEFAULT NULL,
  `Pet_Description_2790` varchar(54) DEFAULT NULL,
  `Weight_Limit_2791` int(11) DEFAULT NULL,
  `Number_of_Pets_2792` int(11) DEFAULT NULL,
  `Assessment_Y/N_2796` varchar(33) DEFAULT NULL,
  `Assessment_Balance_2797` int(11) DEFAULT NULL,
  `Assessment_Type_2798` varchar(33) DEFAULT NULL,
  `Assessment_Amount_2799` int(11) DEFAULT NULL,
  `Earnest_Deposit_2800` int(11) DEFAULT NULL,
  `Annual_Property_Taxes_2801` int(11) DEFAULT NULL,
  `Court_Approval_2802` varchar(33) DEFAULT NULL,
  `Foreclosure_Commenced_Y/N_2804` varchar(33) DEFAULT NULL,
  `Litigation_2805` varchar(33) DEFAULT NULL,
  `Financing_Considered_2806` varchar(60) DEFAULT NULL,
  `Possession_Description_2807` varchar(37) DEFAULT NULL,
  `LA_Phone_2808` varchar(44) DEFAULT NULL,
  `Realtor?_Y/N_2809` varchar(33) DEFAULT NULL,
  `Internet?_Y/N_2810` varchar(33) DEFAULT NULL,
  `LO_Name_2813` varchar(72) DEFAULT NULL,
  `LO_Phone_2814` varchar(44) DEFAULT NULL,
  `Commission_Excluded?__Y/N_2817` varchar(33) DEFAULT NULL,
  `Commission_Variable?__Y/N_2818` varchar(33) DEFAULT NULL,
  `Bonus_S/O_Y/N_2819` varchar(33) DEFAULT NULL,
  `Owner_Licensee_2822` varchar(33) DEFAULT NULL,
  `Additional_Showing_2824` varchar(65) DEFAULT NULL,
  `Power_On_or_Off_2826` varchar(35) DEFAULT NULL,
  `Contingency_Desc_2829` varchar(47) DEFAULT NULL,
  `Sellers_Contribution_$_2830` decimal(14,2) DEFAULT NULL,
  `Amt_Owner_Will_Carry_2831` int(11) DEFAULT NULL,
  `Property_Condition_2832` varchar(36) DEFAULT NULL,
  `Legal_Location_Township_2833` int(11) DEFAULT NULL,
  `Legal_Location_Range_2834` int(11) DEFAULT NULL,
  `Legal_Location_Section_2835` int(11) DEFAULT NULL,
  `Great_Room_Y/N_2840` varchar(33) DEFAULT NULL,
  `Litigation_Type_2841` varchar(52) DEFAULT NULL,
  `NOD_Date_2842` datetime DEFAULT NULL,
  `Repo/Reo_Y/N_2843` varchar(33) DEFAULT NULL,
  `Public_Address_Y/N_2858` varchar(33) DEFAULT NULL,
  `CommentaryY/N_2859` varchar(33) DEFAULT NULL,
  `AVM_Y/N_2860` varchar(33) DEFAULT NULL,
  `Public_Address_2861` varchar(132) DEFAULT NULL,
  `SP/LP_2864` decimal(14,2) DEFAULT NULL,
  `Auction_Date_2878` datetime DEFAULT NULL,
  `Auction_Type_2879` varchar(42) DEFAULT NULL,
  `Photo_Excluded_2883` varchar(33) DEFAULT NULL,
  `Additional_AU_Sold_Terms_2890` varchar(39) DEFAULT NULL,
  `Temp_Off_Mrkt_Status_Desc_2892` varchar(40) DEFAULT NULL,
  `T_Status_Date_2893` datetime DEFAULT NULL,
  `DocumentFolderID_2903` int(11) DEFAULT NULL,
  `DocumentFolderCount_2904` int(11) DEFAULT NULL,
  `PriceChgDate_2908` datetime DEFAULT NULL,
  `City/Town_2909` varchar(41) DEFAULT NULL,
  `SUBDIVISION_NAME_2911` varchar(62) DEFAULT NULL,
  `Existing_Rent_2912` int(11) DEFAULT NULL,
  `Accessibility_Features_2925` varchar(200) DEFAULT NULL,
  `Spa_Description_2926` varchar(53) DEFAULT NULL,
  `Green_Features_2927` varchar(67) DEFAULT NULL,
  `Green_Year_Certified_2929` int(11) DEFAULT NULL,
  `Green_Certifying_Body_2930` varchar(39) DEFAULT NULL,
  `Green_Certification_Rating_2931` varchar(40) DEFAULT NULL,
  `Water_Heater_Description_2932` varchar(67) DEFAULT NULL,
  `Active_DOM_2940` int(11) DEFAULT NULL,
  `Sale_Type_2941` varchar(40) DEFAULT NULL,
  `Gated_Y/N_2946` varchar(33) DEFAULT NULL,
  `State_2963` varchar(34) DEFAULT NULL,
  `Solar_Electric_2978` varchar(38) DEFAULT NULL,
  `Age_Restricted_Y/N_2983` varchar(33) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


```

**Comment by jmancusi** [comment]
Mark,

You are amazing! I have been trying to find something like this for the
last couple of weeks! Thank you so much!

**Comment by troydavisson** [comment]
As mentioned, the schemas from server to server can be drastically different, so including an example would only serve as a waste of time for you to learn from. For example, if you're trying to determine how to figure out whether a property is waterfront, there could be several different ways someone might provide details like that (yes/no, body name, body type, feet frontage, etc.).

**Comment by jmancusi** [comment]
I would have to disagree on it being a waste of time. I am currently in a
situation where I wont have access to the MLS listings I need for another
couple of months, but I am working on developing a CRM for the company.
Having a realistic schema, even if it needs to be adjusted, as I am sure it
will since I will be dealing with 7 different MLSs ... allows me to
conceptualize the data and get some basics setup, which will save me time
in the long run.

Thank you for your work on this project, look forward to working with it.
