### ISSUE TITLE
Does not authenticate for mlslistings.com

### ISSUE THREAD

**Issue by shaikhzaid** [troydavisson/PHRETS#103]
Hi, I am integrating with mlslistings.com but not getting authenticated. What I found in their docs is below. I am aware that PHPRets can do digest authentication but even enabling that does not allow to login. Either I get 401 or 403. Am I doing something wrong, your help would be highly appreciated.

Excerpts from their docs below.
The MLSListings Data Server uses digest authentication (as described in RFC 2617) to authenticate users.  As described in that RFC, when a client sends a login request to the server without credentials, the server response with a challenge (HTTP 403 Response) containing several items of information including a generated number called a nonce.**  The client responds with an MD5 digest of the username, password, realm, and this nonce value**.   If the server recognizes this digest as referring to a valid user, it logs that session in and is ready to accept additional transactions.

Thanks,
Zaid

**Comment by troydavisson** [comment]
Can you confirm that http://retsmd.com/auth is not able to authenticate correctly?  Have you verified that your credentials work with a different RETS client?

**Comment by shaikhzaid** [comment]
Thanks for your quick reply..turned out that the service provider changed the password.

All is good now. Thank you for your time and reply.



Thanks,
Zaid
