### ISSUE TITLE
Missing close parenthesis on subquery

### ISSUE THREAD

**Issue by dreamcoder8** [troydavisson/PHRETS#104]
I am getting "Missing close parenthesis on subquery" error while trying to get listings using RETS

Here is the code query I am passing

$results = $rets->Search('Property', '1', "(138=2016-01-01+),(37=|601,602,603,604,605,606),(242=|ER,S,X),(68=3+),(122=3+)",
		[
        'QueryType' => 'DMQL',
        'Count' => 1, 
        'Format' => 'COMPACT',
        'Limit' => 99999999,
        ]);

**Comment by morr0350** [comment]
It's been a while since you reported this, but, by any chance is this an Interealty RETS server?  In my experience, they do not support lists of criteria, such as in the clause:
`(37=|601,602,603,604,605,606)`

**Comment by dreamcoder8** [comment]
Thanks for your response. We figured it out, it was problem from provider as they have different column names/indexes so 37 wasn't relevant for search we were trying to perform.
Thanks again. Have a nice day ahead.
