### ISSUE TITLE
Uncaught Exception: Curl Error

### ISSUE THREAD

**Issue by Aeyzaz** [troydavisson/PHRETS#105]
Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 56: See http://curl.haxx.se/libcurl/c/libcurl-errors.html' in

**Comment by troydavisson** [comment]
This is most likely caused by some kind of network interruption while communicating with a server.  I suspect a retry would fix it.

**Comment by Aeyzaz** [comment]
Thanks! the issue was resolved long ago.
