### ISSUE TITLE
SearchQuery Order By?

### ISSUE THREAD

**Issue by dcolumbus** [troydavisson/PHRETS#108]
Is there a way to order the results by a specific value?

```
$search = $rets->SearchQuery("Property", "Resi", "(LA_agent_ID=1234)",
			array(
				"Format" => "COMPACT-DECODED",
				"Select" => "LA_agent_ID,street_no,street,date_list,date_sold,status",
				"RestrictedIndicator" => "****",
				"StandardNames" => 0
			)
		);
```

I'd like to order the results by `date_list`, oldest to newest...

**Comment by hatzopoulos** [comment]
RETS does not support the `ORDER BY` concept for results. 

Any ordering of results is controlled by the RETS server or possibly through some custom mechanism, although I've never personally seen or worked with an implementation that had it.

FYI, the same question was asked on the forum, https://groups.google.com/forum/#!topic/phrets/kzEEruN1das
