### ISSUE TITLE
Authentication Failure: Invalid login or password supplied. See: http://flexmls.com/rets/e/22  ReplyCode="20037"/

### ISSUE THREAD

**Issue by sandeepkundu4344** [troydavisson/PHRETS#109]
@troydavisson   
when calling login function $bulletin =$rets->Login();	

I am getting below reponse as $xml 
on Live Server 

```
xml <RETS ReplyText="Authentication Failure: Invalid login or password supplied. See: http://flexmls.com/rets/e/22" ReplyCode="20037"/>

<RETS ReplyCode="0" ReplyText="Success">

  <RETS-RESPONSE>
MemberName=fl.rets.pvolmert
User=fl.rets.pvolmert,MEMBER,1,20160318202045145540000000
Broker=RETS_OFFIC
MetadataVersion=01.03.19423
MetadataTimestamp=2016-07-07T23:31:49Z
MinMetadataTimestamp=2016-07-07T23:31:49Z
Login=/rets2_2/Login
Search=/rets2_2/Search
GetMetadata=/rets2_2/GetMetadata
X-SampleLinks=/rets2_2/Links
X-SupportSite=http://flexmls.com/rets/
X-NotificationFeed=http://retsgw.flexmls.com/atom/feed/private/atom.xml
GetObject=/rets2_2/GetObject
Logout=/rets2_2/Logout
X-ApiAccessSettings=/rets2_2/API
</RETS-RESPONSE>
</RETS>
```

but same code working fine in my dev server but on client production server its giving authentication error.

on Dev Server

```xml
<RETS ReplyCode="0" ReplyText="Success">

  <RETS-RESPONSE>
MemberName=fl.rets.pvolmert
User=fl.rets.pvolmert,MEMBER,1,20160318202045145540000000
Broker=RETS_OFFIC
MetadataVersion=01.03.19423
MetadataTimestamp=2016-07-07T23:31:49Z
MinMetadataTimestamp=2016-07-07T23:31:49Z
Login=/rets2_2/Login
Search=/rets2_2/Search
GetMetadata=/rets2_2/GetMetadata
X-SampleLinks=/rets2_2/Links
X-SupportSite=http://flexmls.com/rets/
X-NotificationFeed=http://retsgw.flexmls.com/atom/feed/private/atom.xml
GetObject=/rets2_2/GetObject
Logout=/rets2_2/Logout
X-ApiAccessSettings=/rets2_2/API
</RETS-RESPONSE>
</RETS>
'''

**Comment by sandeepkundu4344** [comment]
please let me know why same code is running good and authentication working in dev but on live server its giving authentication error.

**Comment by troydavisson** [comment]
Are you still having issues logging into this RETS server?  It doesn't appear so, but I wanted to double check.

**Comment by troydavisson** [comment]
Since you're accessing the Flexmls RETS server here, if you're still having issues with this, please email rets-support@flexmls.com

**Comment by saumil1234** [comment]
Hi,

I am facing same issue. Code works fine in local but not working on production server. I am getting below response.

<?xml version="1.0"?> <RETS ReplyText="Authentication Failure: Invalid login or password supplied. See: http://flexmls.com/rets/e/22" ReplyCode="20037"/> <RETS ReplyCode="0" ReplyText="Success"> <RETS-RESPONSE> M

Not sure what is causing the issue. I have googled it but don't find any promising solutions. Pls let me know if someone has fixed it or have solution.
