### ISSUE TITLE
Response has COUNT, but no DATA records

### ISSUE THREAD

**Issue by ted-at-roar** [troydavisson/PHRETS#110]
We use phRETS in our setup and it's working successfully across 5 separate RETS providers, except one is being problematic.

Randomly, we're receiving a response that looks like this:

```XML
<RETS ReplyCode="0" ReplyText="V2.6.0 761: Success">
<COUNT Records="1402"/>
<DELIMITER value="09"/>
<COLUMNS>	ListingKey	</COLUMNS>
</RETS>
```

I know this is not a direct phRETS problem, but I've been battling this situation for a week, the MLS board keeps telling us that the problem is at our end. I haven't found anything else online that matches this particular situation.

The board is SRAR (Southland Regional, California), which uses the CARETS data system

In this particular case, phRETS does not detect any errors, even though there's a COUNT, but no DATA records. It happily continues on its way because the status was "Success". Again, this is completely random, happens only with one or two Property resources during an update of several Property, Agent, Office and OpenHouse resources.

This only happens with queries that have "Select=ListingKey". All other queries work properly.

**Has anyone ever seen a situation like this?** It happens randomly, and never with the same Resource twice in a row. From all accounts, this definitely seems like a provider issue, but again SRAR has not been willing to accept that this is a problem at their end since nobody else is reporting the same problem (typical response). :) 

Do you interpret the above response as invalid, or is that a perfectly valid response? It doesn't make sense that there would be no DATA records at all.

I appreciate any feedback you may have.

**Comment by troydavisson** [comment]
Do you have details of what your request was which produced that response?
A couple of guesses:


   1. Somehow, you're sending a COUNT of 2 rather than COUNT of 1.  If you
   could show a debug of the request being made which produced this response,
   that would help immensely.  COUNT 0 = no count, data only.  COUNT 1 =
   count + data.  COUNT 2 = no data, count only
   2. You're paginating through the results using OFFSET but you've paged
   beyond the last record (for example, maybe you're trying to pull page 3 of
   a 1000 record page, and 1,402 records only needs 2 pages).
   3. Something is especially wonky with that RETS server

Having confirmation about what the client side is asking for should give
pretty quick confirmation to the source of the issue.

**Comment by ted-at-roar** [comment]
Request:

```
GET /cornerstone/search?SearchType=Property&Class=RES&Query=(CARETSListingStatus=|50041200437)&QueryType=DMQL2&Count=1&Format=COMPACT-DECODED&Limit=99999999&Offset=1&Select=ListingKey&StandardNames=0
```
_(url-decoded for clarity)_

I can confirm:
1. Count=1
2. Offset=1
3. Limit=99999999  (ie. intended as "None")
3. Server is definitely wonky, but so far it's been difficult having them take my reports seriously. :)

Identical requests (generated by same routine) are coming back properly. These incomplete responses are _random_, and only happening for certain Property resources.

First time noticing that the request is being sent with Limit=99999999 instead of Limit=None. I'd need to review the RETS docs to see if this should be None. phRETS is handling this request composition, so I assumed this was all happening correctly, but maybe their server doesn't like this?

Another possibility is an unclean cache at their end that's causing certain parameters (eg. Offset) to be passed from one request to the next even though I've provided a new Offset=1.

So, by your observation, the response that I provided above is not valid? If COUNT has a value, there should be at least one DATA record, correct (where Offset=1)?

**Comment by troydavisson** [comment]
Your request appears to be completely valid.

Using the defined Limit number is intentional and should be fine (which
seems to be confirmed with at least most of your requests against that RETS
server).

Something else you included in your request is interesting to me.  Do you
happen to know how long it takes for the RETS server to reply to that
request?  Is it, by chance, almost exactly 60 seconds?

**Comment by ted-at-roar** [comment]
Here's the debug log for the same request that has been working successfully from my development machine (exact same codebase on development and production)...

```
* Found bundle for host carets.csrets.mris.com: 0x7f9f81c84400 [can pipeline]
* Re-using existing connection! (#0) with host carets.csrets.mris.com
* Connected to carets.csrets.mris.com (74.217.86.68) port 6103 (#0)
* Server auth using Digest with user '*******'
> GET /cornerstone/search?SearchType=Property&Class=RES&Query=%28CARETSListingStatus%3D%7C50041200437%29&QueryType=DMQL2&Count=1&Format=COMPACT-DECODED&Limit=99999999&Offset=1&Select=ListingKey&StandardNames=0 HTTP/1.1
Host: carets.csrets.mris.com:6103
Authorization: Digest username="********", realm="users@mris.com", nonce="31343639313138373037363837207b3152b724f7629f96c81122a0f3209d", uri="/cornerstone/search?SearchType=Property&Class=RES&Query=%28CARETSListingStatus%3D%7C50041200437%29&QueryType=DMQL2&Count=1&Format=COMPACT-DECODED&Limit=99999999&Offset=1&Select=ListingKey&StandardNames=0", response="103bdd600d16ec3c99dd7fef80ad5d82", opaque="6e6f742075736564"
Accept: */*
Cookie: RETS-Session-ID=300234106777
RETS-Version: RETS/1.7.2
User-Agent: RETS-Connector1.2/1.0

< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 21 Jul 2016 16:31:55 GMT
< Content-Type: text/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< Keep-Alive: timeout=20
< X-Copyright: Copyright 2016 Metropolitan Regional Information Systems, Inc., unauthorized use is prohibited.
< Cache-Control: private
< RETS-Version: RETS/1.7.2
* Replaced cookie RETS-Session-ID="300234106777" for domain carets.csrets.mris.com, path /, expire 0
< Set-Cookie: RETS-Session-ID=300234106777; Path=/
< 
* Connection #0 to host carets.csrets.mris.com left intact
<RETS ReplyCode="0" ReplyText="V2.6.0 761: Success">
<COUNT Records="3386"/>
<DELIMITER value="09"/>
<COLUMNS>	ListingKey	</COLUMNS>
<DATA>	90123473223	</DATA>
<DATA>	90123504977	</DATA>
<DATA>	90123855548	</DATA>
  ... (intentionally truncated) ...
</RETS>
```

and here's the relevant log entries from my application that wraps around phRETS:

```
2016-07-21T16:31:47+00:00 [info] Connected to 'SRAR' RETS server (http://carets.csrets.mris.com:6103/cornerstone/login)
2016-07-21T16:31:47+00:00 [info] Executing RETS Search - Resource: Property, Class: RES, Query: (CARETSListingStatus=|50041200437), Select: ListingKey
2016-07-21T16:31:55+00:00 [info] Beginning database transaction.
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
2016-07-21T16:31:59+00:00 [info] Database transactions committed.
2016-07-21T16:31:59+00:00 [info] 3386 records of type (Resource: Property, Class: RES) inserted or updated.
```

Seems that it took 8 seconds get the full response.

One possibility, although they've denied this, is that they are somehow throttling requests from our production machine, although that should return an error instead of "Success" response with no data.

**Comment by ted-at-roar** [comment]
So it turns out that passing Offset=1 and Limit=99999999 was causing the server to be unable to prepare a response. Removing these two parameters seems to have made the problem go away. It's possible that the records on the server were changing so quickly that Offset=1 could not be handled.

The board SRAR has been helpful in resolving this issue. Their techs suggested that Offset and Limit were unnecessary and questioned why we were passing these in. So thanks to them for that observation.

**Comment by Lewkow** [comment]
@ted-at-roar you saved me days of trial and error with this same issue, thank you much for posting what fixed it for you.
