### ISSUE TITLE
terminology mixup

### ISSUE THREAD

**Issue by michael-lynch** [troydavisson/PHRETS#114]
This may be an issue with the docs, or it may just be me not understanding this, but in your first example you reference the `Search()` method like this:

`$rets->Search('Property', 'A', '*', ['Limit' => 3, 'Select' => 'LIST_1,LIST_105,LIST_15,LIST_22,LIST_87,LIST_133,LIST_134']);`

To me, this looks like `$rets->Search($resource, $status, $class, $query)` but then further down in the README, it's referenced like this:

`$rets->Search($resource, $class, $query);`

I'm confused because I thought RETS classes were "CND," "COM", "RES" etc. and "A" represents the "status."

Is the terminology off? Or am I not getting something?

I am trying this:

`$results = $rets->Search('Property', 'A', '*');`

A `\PHRETS\Models\Search\Results` object is returned but with 0 results. However, I see results in retsmd.com. What am I missing? I tried reordering the parameters in case that was the problem, but that didn't work either.

**Comment by troydavisson** [comment]
The primary RETS server I work against uses class names that are alphabetical letters, so that drives a lot of the examples I often give.  Normally the "A" property type refers to Residential, "B" is often Land, etc.

**Comment by michael-lynch** [comment]
Ah, ok. Thanks for clearing that up.

Knowing that now, I tried `$rets->Search('Property', 'RES', '*')` but it still didn't work. I tried the other classes (COM, CND) but those didn't work either.

My exact instructions were:

```
1. Connect via RETS client.
2. Set query to; status=’A’.
3. Download separately for each class (RES(freehold), CND(condo), COM(commercial)).
```

With that in mind, I also tried:

`$rets->Search('Property', 'RES', '(status=A)');`

.. but this also returned 0 results. I'm starting to think this might be a syntax issue or something. Any tips?

**Comment by michael-lynch** [comment]
I'm using the TREB server and I found the proper syntax here:

https://github.com/moeloubani/wptrebrets/blob/master/inc/Feed.php

It turns out I needed a second set of brackets around my query and the class is actually "ResidentialProperty," not "RES."

This works for me:

`$rets->Search('Property', 'ResidentialProperty', '((status=A))');`
