### ISSUE TITLE
can't get photo object

### ISSUE THREAD

**Issue by michael-lynch** [troydavisson/PHRETS#116]
I am using the TREB server to get properties and I want to get the image for each property.

I am able to get each property and then for each, I try:

`$objects = $rets->GetObject('Property', 'Photo', $propertyMLNumber);`
(where `$propertyMLNumber` equals an `Ml_num` value, such as `C3446872`)

I get this error object:

```
PHRETS\Models\Object Object
(
    [content_type:protected] => text/xml;charset=utf-8
    [content_id:protected] => 
    [object_id:protected] => 0
    [mime_version:protected] => 1.0
    [location:protected] => 
    [content_description:protected] => 
    [content_sub_description:protected] => 
    [content:protected] => 

    [preferred:protected] => 
    [error:protected] => PHRETS\Models\RETSError Object
        (
            [code:protected] => 0
            [message:protected] => 
        )
)
```

What am I missing?

**Comment by michael-lynch** [comment]
I have contacted our support correspondent at the Toronto Real Estate Board (TREB) and apparently I'm not the only one who has this issue. Has anyone had success pulling images from the TREB server?

**Comment by thezenmonkey** [comment]
TREB requires optional parameters for image reqests

`$objects = $rets->GetObject('Property', 'Photo', $propertyMLNumber, "*", 0);`

**Comment by michael-lynch** [comment]
Hmm... I added those parameters but it still didn't work. I found this error in the response though:

```
<RETS ReplyCode="20407" ReplyText="Unauthorized Retrieval: The object could not be retrieved because it requests an object to which the supplied login does not grant access."/>
```

This is odd, as I'm sure we have access to the `Photo` object. I logged into http://retsmd.com to confirm that. Is there some other reason why this error may be thrown?

**Comment by michael-lynch** [comment]
Ah, ok, I think I got it. I was given two usernames - one to download all RETS data and one to only download the ML numbers of active listings. I was using the latter when I should have been using the former. I wish they had some documentation to make this clear!

**Comment by thezenmonkey** [comment]
Yup, the two user names are ususally teh cause of most of the issues

**Comment by lillorme** [comment]
@michael-lynch could you explain how to get the content_id and the object_id or show me a code example?
`$objects = $rets->GetObject('Property', 'Photo', $content_id, $object_id', 1);`

**Comment by michael-lynch** [comment]
@lillorme In your case, `$content_id` would be the MLS number (i.e. `C3446872`). I believe the `$object_id` is referencing the pariticular photo you want, but you can set a wildcard here to reference _all_ photos.

```
$objects = $rets->GetObject('Property', 'Photo', 'C3446872', '*', 0);

foreach($objects as $key => $object) {
    if(!$object->getError()) {
        $data = $object->getContent();
        $file = $key.'.jpg';
        file_put_contents('/img/'.$file, $data);
    }
}
```
This would get all the images for `C3446872` and add them to an `/img/` directory named `0.jpg`, `1.jpg`, `2.jpg` etc.
