### ISSUE TITLE
Unique ID value is not included in downloaded Photo Object 

### ISSUE THREAD

**Issue by MonkeyTrainer12** [troydavisson/PHRETS#117]
When I use GetObject() to pull down a photo data object, I can use getContentID() to get the parent's Unique ID ("Table_MUI") and getObjectId() which gives me the "Order" value.  If you combine these two, you get a unique item reference, but when I look at the values in the Object, it doesn't include the Matrix record's "matrix_unique_id" value.  We built our own image storage system to use that image's official Unique ID as the filename, and I believe a lot of users would find the photo Object more flexible if it included the system's own unique value rather than one we have to build.  I believe it would be pretty simple to include that data and to add a getUid() method to the Object.

I'll tinker with it on my own install, and if I get working, I'll make a pull request (I am relatively new to GitHub).  If you decide it is worthwhile and can get it done faster, please do.

**Comment by troydavisson** [comment]
Are you still seeing this issue with their server?

**Comment by MonkeyTrainer12** [comment]
Yes, this issue persists.  I have been forced to work around it, rather inefficiently.

This is the object structure I get from downloading a photo:

PHRETS\Models\Object Object
(
	[content_type:protected] => ...
	[content_id:protected] => ... /*-- The "Table_MUI" value, shared by all photos for this property --*/
	[object_id:protected] => ... /*-- The sequence number for the photo, 0 being the preview --*/
	[mime_version:protected] => ...
	[location:protected] => ...
	[content_description:protected] => ...
	[content_sub_description:protected] => ...
	[content:protected]=> ...
	[preferred:protected] => ...
	[error:protected] => ...
)

I'm hoping the object can be modified to deliver the photo's "matrix_unique_id" value, perhaps under [unique_id:protected].

**Comment by troydavisson** [comment]
I think I better understand what you're after there.

According to the spec, `Content-ID` represents (in the case of listings) the listing's primary key value, and `Object-ID` represents the "sequence" number so you know what order those objects go in.  There's no existing capability or spot within the GetObject response supported by the spec for the UID of the object itself to be returned.  In some cases, you could maybe find this out by looking at some other attribute in the response (for example, the Flexmls RETS server, when using Location=1, exposes the object's UID in the filename returned in the URL), but generally speaking, the `PHRETS\Models\Object` objects returned from your `GetObject()` call are only able to give you information provided to it by the server, and the object's UID isn't something it gives.

**Comment by wangdebin** [comment]
hello sir

  $rets_modtimestamp_field = "ModificationTimestamp";$previous_start_time = "2010-00-31T00:00:00"; $query = "({$rets_modtimestamp_field}={$previous_start_time}+)";$search = $rets->SearchQuery("Property", 'Residential', $query, array('Limit' => $limit, 'Offset' => $offset, 'Format' => 'COMPACT-DECODED', 'Count' => 1)); 

I've got the information about this house, but I want to get the picture of the house. How can I get the picture of this house? This method is getObjec (GetObject ($resource, $type, $id, $photo_number = *, $location = 0)), there is no house property in the house information inside the ID, or through other ways to obtain, if it is to obtain the other way, can you tell me

**Comment by lillorme** [comment]
I'm new to PHRETS and I would like to know how would I get the content_id to place in the action 
`$photos = $rets->GetObject("Property", "Photo", "$content_ids", "*", 1);`
