### ISSUE TITLE
PHRETS CSV export file showing Total found:0 

### ISSUE THREAD

**Issue by waqar4772** [troydavisson/PHRETS#120]
Hi, there I am trying to fetch data to a CSV file for the Property: "Residential Property" , it is connecting but finds 0 results from the table.
Can anyone help me out with this?

![screenshot_1](https://cloud.githubusercontent.com/assets/22602502/19053980/c73f2a22-89d6-11e6-9d5e-c5ecc2bc6d85.png)

This is the error shown in the browser

![screenshot_2](https://cloud.githubusercontent.com/assets/22602502/19053994/d12130c6-89d6-11e6-9914-7398aed68d2d.png)

This is my Phrets.php file code where it is showing error on line no:1263

![screenshot_3](https://cloud.githubusercontent.com/assets/22602502/19054109/42b7d1ae-89d7-11e6-9402-a8af3c8dc867.png)

And this is my index.php file

**Comment by troydavisson** [comment]
`LIST_87` won't be the correct field name against this server.  You should verify the correct field names by looking at the metadata (www.retsmd.com is a quick way to do that) so you can be sure your requests are performing searches on valid fields.

**Comment by troydavisson** [comment]
Also, it's been brought to my attention that your initial comment included a screenshot which contained your username and password.  I'd ask that you be more careful next time, and to contact the provider of your RETS feed to request that they update your password to something not matching the one shared publicly here.
