### ISSUE TITLE
Session class no error on line 379

### ISSUE THREAD

**Issue by mikeritter** [troydavisson/PHRETS#124]
you actually wrote a comment

`// 20201 - No records found - not exception worthy in my mind`

well, just threw this exception and PHP choked with an Uncaught exception warning.

**Comment by troydavisson** [comment]
What's the exception code that was included in what was thrown?

**Comment by troydavisson** [comment]
OK.  The 20201 is for when pulling records.  I didn't realize there was a separate one for the same sort of condition when using `GetObject`.  I'll make an update for that.

**Comment by mikeritter** [comment]
you're great!

**Comment by mikeritter** [comment]
NOTE:

"I was going to ask why you are not using GetAllObjects() which librets has, but it doesn't look like phrets doesn't support that. Might be something to look at since they have PHP support too."

http://stackoverflow.com/questions/17452336/getting-several-20403-no-object-found-errors-while-downloading-photos-from-r

**Comment by troydavisson** [comment]
For posterity, PHRETS does support that:  only the first 3 parameters on `GetObject` are required (resource, type and content ID).  Not specifying a 4th parameter automatically gets all of the objects.

**Comment by mikeritter** [comment]
man! as it should. down with OOP!

**Comment by mikeritter** [comment]
5.12 Reply Codes
Table 5-1 GetObject Reply Codes  Reply Code Meaning
20400 Invalid Resource The request could not be understood due to an unknown resource.
20401 Invalid Type The request could not be understood due to an unknown object type for the resource.
20402 Invalid Identifier The identifier does not match the KeyField of any data in the resource.
20403 No Object Found No matching object was found to satisfy the request.
20406 Unsupported MIME type The server cannot return the object in any of the requested MIME types.
20407 Unauthorized Retrieval The object could not be retrieved because it requests an object to which the supplied login does not grant access.
20408 Resource Unavailable The requested resource is currently unavailable. 20409 Object Unavailable The requested object is currently unavailable.
20410 Request Too Large No further objects will be retrieved because a system limit was exceeded.
20411 Timeout The request timed out while executing
20412 Too many outstanding requests The user has too many outstanding requests and new requests will not be accepted at this time.
20413 Miscellaneous error The server encountered an internal error.
20414 URL Location Not Supported The server does not support retrieving Objects by URL.
