### ISSUE TITLE
Could not parse DMQL2 Query: Invalid character: '-' 

### ISSUE THREAD

**Issue by masha-andreeva** [troydavisson/PHRETS#125]
I need to get properties from office, which contains "-". For example sTr-28322

My search condition is (ListOfficeMlsId={$officeId}). So '-' is not allowed character. Cannot find how to escape it... Please help.

**Comment by troydavisson** [comment]
Try this instead:

`(ListOfficeMlsId="{$officeId}")`

**Comment by masha-andreeva** [comment]
It's works. Thank you very much!
