### ISSUE TITLE
Cant not find list of Search query optional parameters

### ISSUE THREAD

**Issue by rubydwebguys** [troydavisson/PHRETS#126]
I am unable to get list of optional parameters of search query and how to use them. retsdoc.onconfluence.com/display/rets172/7.4+Optional+Request+Arguments this url also not working. please help.

**Comment by troydavisson** [comment]
These are available under section 7.4 of the RETS spec available at https://www.reso.org/specifications/ (described in more detail with examples there).

They are:

 - `Count` - The Count argument controls whether the server’s response includes a count.  `0` = no count, `1` = count + records, `2` = count only.  PHRETS defaults to `1`
 - `Format` - The Format argument selects one of the three supported data return formats for the query response.  PHRETS only understands `COMPACT` and `COMPACT-DECODED`
 - `Limit` - The Limit argument requests the server to apply or suspend a limit on the number of records returned in the search.
 - `Offset` - The client may specify that a retrieval start at other than the first record in the set of records matching the query by specifying the Offset argument.  Servers may not support this feature.  This is used to paginate through sets of results.
 - `Select` - By default, the server MUST return all fields accessible to the client. The client may select a subset of those fields by specifying the Select argument.
 - `RestrictedIndicator` - In some instances, the server may withhold the values of selected fields on selected records.  When the server restricts the value of a field, it's replaced with whatever you request the restricted indicator to be.  You can use `$record->isRestricted($field)` on each record to determine whether that's happened or not.
 - `StandardNames` - If set to `1`, the server will interpret your incoming request as one that uses the StandardName associated with the fields (both in the query and `Select` statements) and will respond with the StandardName version of values.  If set to `0`, the SystemName is instead used.  PHRETS uses `0` by default.

A select number of servers support other custom extensions through their RETS server (for example, for sorting results) but those aren't defined in the RETS specification.
