### ISSUE TITLE
Can't get commercial image url from the server

### ISSUE THREAD

**Issue by liusqi** [troydavisson/PHRETS#127]
the script looks something like this: 
`$objects = $phRETS->GetObject('Property', 'Photo', $listingID, '*', $location);`

From my understanding, setting location to be 1 should receive an object with url and 0 should receive the actual image content. It works for residential listings, although I can only request content for commercial listing images or the server will respond null. I suppose this is server's problem? Or is there anything I need to do in order to get urls?

**Comment by troydavisson** [comment]
Getting the URL is optional, though I can't say I've seen instances where it's supported for one property type but not another.

To clarify, 1 requests only the headers and the URL.  0 gets headers and the image contents.
