### ISSUE TITLE
isMaxRowsReached bug ?

### ISSUE THREAD

**Issue by rmed19** [troydavisson/PHRETS#129]
Hi,
I try to dump all rets data this is my code  : 

```php
        $config = new \PHRETS\Configuration();
        $config->setLoginUrl($host);
        $config->setUsername($username);
        $config->setPassword($password);
        $config->setRetsVersion($version);

        $rets = new \PHRETS\Session($config);
        $login = $rets->Login();

        $rets->Search("Property", "Listing", "(MatrixModifiedDT=2016-11-04T11:36:11+), (PropertyType=|RES,VER)", [
                'QueryType' => 'DMQL2',
                'Count' => 1, // count and records
                'Format' => 'COMPACT-DECODED',
                'Limit' => 99999999,
                'StandardNames' => 0,
            ]);

            echo $retsArray->getTotalResultsCount(); // return 20536
            echo $retsArray->getReturnedResultsCount(); // return 5000
            echo $retsArray->isMaxRowsReached(); // return  true
```

Like we can see the returnedResultsCount is more less then TotalResultsCount but isMaxRowsReached is true instead of false.

**Comment by troydavisson** [comment]
Pass `true` as the 5th parameter of your `Search()` call and you should see different results.

In this case, I think it's acting as it should be:  you've asked for a large list of results but the server has denied that and instead only given you a partial set (returned less than total) and has indicated that the results given to you in that batch reached the server's maximum (maxrows), so it's their way of instructing you to continue paginating through the results.

Passing `true` as the 5th parameter will have PHRETS automatically paginate for you which should cause you to have all records returned (even if it took several requests to the RETS server to gather those).

If you add a Monolog logger instance to `$rets` (make sure monolog is required with Composer and see the first example in the PHRETS readme), you'll be able to see it work through the pages.

**Comment by rmed19** [comment]
Hi,
I make some tests when the maxRowsReached the method isMaxRowsReached retrn false instead of true.

**Comment by troydavisson** [comment]
If you're now using `true` as the 5th parameter, that's expected.  MaxRows being reached represents that the server has limited the results given back and that there's more to grab.

**Comment by troydavisson** [comment]
Probably also worth noting that a healthy number of RETS servers either don't implement pagination (the `Offset` parameter, which is optional according to the spec) or don't implement it correctly, so you may be running into some odd behaviors unrelated to PHRETS directly.
