### ISSUE TITLE
Get Meta Data

### ISSUE THREAD

**Issue by ahsan154** [troydavisson/PHRETS#130]
Fatal error: Uncaught exception 'PHRETS\Exceptions\RETSException' with message 'No Metadata Found' in D:\wamp\www\mls_fl\vendor\troydavisson\phrets\src\Session.php on line 379

( ! ) PHRETS\Exceptions\RETSException: No Metadata Found in D:\wamp\www\mls_fl\vendor\troydavisson\phrets\src\Session.php on line 379

and here is my CODE:

//http://rets.mfrmls.com/contact/rets/login is the server login URL
$connect = $rets->Login();

$system = $rets->GetSystemMetadata();

$resources = $system->getResources();
$classes = $resources->first()->getClasses();

$classes = $rets->GetClassesMetadata('Property');

$objects = $rets->GetObject('Property', 'Photo', '00-1669', '*', 1);

$fields = $rets->GetTableMetadata('Property', 'A');
var_dump($fields[0]);
echo "35_<br/>";
$results = $rets->Search('Property', 'A', '*', ['Limit' => 10, 'Select' => 'LIST_1,LIST_105,LIST_15,LIST_22,LIST_87,LIST_133,LIST_134',true]);

foreach ($results as $r) {
    var_dump($r);
}

**Comment by ahsan154** [comment]
FYI, i am able to connect to the server

**Comment by ahsan154** [comment]
FYI, i am able to connect to the server

**Comment by troydavisson** [comment]
You'll want to log into www.retsmd.com using your RETS credentials and learn the data formats provided there.  I would guess that "A" isn't a valid Class under the "Property" Resource.  You'll need to substitute actual values in place of the example you're currently using.
