### ISSUE TITLE
only fetch active homes and delete non from database   CAKE PHP

### ISSUE THREAD

**Issue by Iconcrmtech** [troydavisson/PHRETS#132]

**Comment by troydavisson** [comment]
I've modified your comment to remove the code you posted, which included sensitive account credentials for a number of services.  Please be more careful next time.

**Comment by Iconcrmtech** [comment]
I modified it too I thought I saved it thanx

**Comment by Iconcrmtech** [comment]
Do you know how to remove everything except the active ones that includes deleting the ucb and ccbs

**Comment by troydavisson** [comment]
I suggest reviewing https://www.flexmls.com/developers/rets/tutorials/how-to-efficiently-replicate-rets-data/

**Comment by Iconcrmtech** [comment]
is there a solution for pulling expiredes from the rets
