### ISSUE TITLE
Installing PHRETS on Linux

### ISSUE THREAD

**Issue by Bilbosax** [troydavisson/PHRETS#134]
I have a system set up on a Windows 10 installation working perfectly.  Because of our final delivery system, I need to transfer everything to a Linux machine.  To get PHRETS onto the linux machine, I place the code shown below into my compser.json file:

{
"require": {
"troydavisson/phrets": "2.*"
}
}

Finally, I run **php composer.phar install** in the bash shell on the Linux machine.  It installs the vendor folder with all of the required dependencies, but it is loading troydavisson/phrets (2.0), not 2.2.  So when I run my php scripts in Linux to do the RETS pull, I am getting the error 

    PHP Fatal error:  Call to undefined method PHRETS\Models\Search\Results::toArray() in /var/www/html/RETSandDatabase/RETStoDatabaseUpdate.php on line 43

I am converting my results from the RETS pull to an array using a method called toArray() that PHRETS provides on my Windows machine, but sure enough, it does not exist in the code that was downloaded and installed in version 2.0.   I may be wrong, but I am assuming that this was a feature added by version 2.2 that does not exist in version 2.0? If this is indeed what the problem is, how do I force it to download and install 2.2 instead of 2.0?  If it is not the problem, why is the method toArray() missing?

Thanks!

P.S.  I already tried placing "2.2" in the compser.json file instead of "2.*", it did not work.

**Comment by troydavisson** [comment]
In that instance, it sounds like Composer has detected that your Linux server is only capable of satisfying the requirements for the earlier version (I'd guess version of PHP).  What version is that server running compared to your local Windows machine?

**Comment by Bilbosax** [comment]
Hi Troy. I have a quick question about downloading photos using PHRETS. For my initial photo download of a market, I don't want to use getObject if I don't have to because I would need to execute it 56k times in Indianapolis to get all of the photos for the properties that I have. I would much rather just do a regular query on the Media Resource/Media Class to pull the information that I need in bulk quantities based on modified dates. When I run a regular query, I get a blank set of quotes for the MediaPath, and I have figured out that it is not giving me that value because I have not stated in my query the data type that I want - either 'Photo' or 'LargePhoto'. This is what my current query looks like: 

$resource = 'Media'; 
$class = 'Media'; 
$fields = 'matrix_unique_id,MediaPath, ModifiedDate,Size,Table_MUI'; 

$listings = array(); 

$query = '(ModifiedDate='.$date.'T00: 00:00.000-'.$today.'T23:59:59. 000)'; 
$result = $rets->Search($resource, $class, $query, array('Select'=>$fields, "Format"=>"COMPACT-DECODED")); 
$listings = $result->toArray(); 
echo count($listings)."\n"; 

foreach ($listings as $listing) { 
echo $listing['MediaPath']."\n"; 
} 


This code just echos a bunch of empty strings. Is there a way to set the object type to Photo or LargePhoto when you are doing just a general query? 

Thanks, 
Bill Spence

**Comment by troydavisson** [comment]
I don't believe the Matrix RETS server has a way to do that through their `Media` resource.  In order to specify the size you want, it looks like you'll need to use `GetObject`.
