### ISSUE TITLE
Infinite memory usage on searches - NOT PCRE

### ISSUE THREAD

**Issue by reol-nbessette** [troydavisson/PHRETS#135]
Bear with me here. Let me be upfront about one thing: this has nothing to do with PCRE (preg_replace, preg_match, etc.). Over and over again in issues people are trying to pin PHRETS's memory usage problem on PCRE, but I can say with absolute certainty that PCRE has *nothing* to do with it. Please put PCRE out of your mind; it is not the problem, and you need to stop looking at it as a scapegoat. I have tracked the real issue down to a certain level, but the code is complex enough that it's really hard to pin the problem down to a very exact cause.

What is happening: every time you call `Search()` on a session, memory usage explodes. The closest I've been able to diagnose so far is in the `addRecord()` method of `src/Models/Search/Results.php`. If you comment out the line `$record->setParent($this);`, you wind up with zero memory leak. For my minimal test case of simply paginating a resource and class type, it also doesn't affect the functionality of the script.

The weird-ass part of this leak is that if after every call to the session's `Search()` method you call `gc_collect_cycles()`, the memory usage does does not increment at all after the second iteration. I haven't seen a memory usage bug like this ever since PHP 5.3, which introduced cleanup of circular references between objects. This library must be doing something really odd to be managing this leak, whether it's the library's fault or a rare edge case of fooling PHP into not being able to garbage collect something. 

Minimal test case (look at the commented `gc_collect_cycles()` comment right at the end):

```php
$session = new \PHRETS\Session(
    (new \PHRETS\Configuration())
        ->setLoginUrl('http://example.com/login')
        ->setUsername('username')
        ->setPassword('password')
);

$session->Login();

foreach ($session->GetResourcesMetadata() as $resourceId => $resource) {
    $resourceKey = $resource->getKeyField();

    foreach ($resource->getClasses() as $classId => $class) {
        $lastId = 0;

        do {
            fwrite(STDERR, number_format(memory_get_usage() / 1024 / 1024, 2) . " MB\n");

            $search = $session->Search(
                $resourceId,
                $classId,
                $resourceKey . '=' . ($lastId + 1) . '+',
                ['Limit' => 500]
            );

            $lastId = $search->last()->get($resourceKey);

            // commented out, infinite memory usage. uncommented, no leak at all
            // gc_collect_cycles();
        } while ($search->count() > 0);
    }
}
```

**Comment by troydavisson** [comment]
Thanks for this information.  To be clear, the PCRE memory usage issue was primarily for version 1 of this library which used a very different model for doing things.  The primary issue with 2.0 does relate to object references, so I've been working on a few approaches that would make this better.  The ideas and research you posted here helps a lot and gives me some additional ideas, thanks.

**Comment by troydavisson** [comment]
The `2.3` dev branch contains some changes which should help with this.  If you could try and version and report back with your findings on memory usage, I'd appreciate it.

**Comment by troydavisson** [comment]
Version 2.3 has been released and includes some changes which should address this.  Please give the latest version a try if able.
