### ISSUE TITLE
Rets Search Query Sort

### ISSUE THREAD

**Issue by heliosmar** [troydavisson/PHRETS#136]
Hi,

I need get the search in order Desc but I don´t know how make this.

$search = $rets->SearchQuery(
		'Property',								
		'ResidentialProperty',										
		'(id=4511-),(status=1)',		
		array(
			'Format'	=> 'COMPACT-DECODED',
			'Select'	=> 'id,title,price_current,status,property_type',
			'Count'		=> 1,
                        'Order By'   => 'id Desc', // I try this, 👎          

			)	
	);

**Comment by troydavisson** [comment]
Sorry, RETS doesn't support sorting.  You'd have to download the record set locally into a database and sort from there.
