### ISSUE TITLE
Need latest guzzlehttp/guzzle supported

### ISSUE THREAD

**Issue by wyg27** [troydavisson/PHRETS#137]
Hi,

Now the PHRETS 2.* require guzzlehttp/guzzle < 6.0, it makes me cannot install it in my Laravel 5.* project, since other composer packages need latest guzzlehttp/guzzle.

Thanks for your code and have a good day.

**Comment by steveheinsch** [comment]
2.3 uses guzzle 6.
use this in composer:
"troydavisson/phrets": "2.3.*@dev"
