### ISSUE TITLE
Clearing metadata

### ISSUE THREAD

**Issue by Dyceman** [troydavisson/PHRETS#141]
Is there a way to clear the metadata that is stored?

Things I've tried were
- Clearing the CookieJar with the **clear** function.

**Comment by troydavisson** [comment]
The metadata isn't stored in PHRETS.  Other than what's held in the objects retrieved, the cookie jar just holds onto cookies need for the authenticated session with the server.

What problem are you having?

**Comment by Dyceman** [comment]
I have a commercial and residential login, both have separate login urls. I can login successfully to the residential but not the commercial using PHPRets, so I tried logging in using RetsMD and was able to login on both.

**Comment by troydavisson** [comment]
Do you have the same issue with www.retsmd.com/auth ?

**Comment by Dyceman** [comment]
> so I tried logging in using RetsMD and was able to login on both.

**Comment by troydavisson** [comment]
> Do you have the same issue with www.retsmd.com/auth ?

**Comment by Dyceman** [comment]
The rets login server is white listed so, no it won't work. I installed RETSMD on my server and was able to login to both.

**Comment by troydavisson** [comment]
What's the login URL for the commercial feed?

**Comment by Dyceman** [comment]
Sorry but I can't give you that because I signed a contract.

I can give you the error I am getting though.
