### ISSUE TITLE
Problem with Search Query

### ISSUE THREAD

**Issue by vah7id** [troydavisson/PHRETS#147]
Hi troy,

I just found your great library and I have a problem with search query.
When I Call this function always get this message "

af course I authorize my credentials before call search like this : 

```
$rets = new \PHRETS\Session($config);
$connect = $rets->Login();
echo $connect;
```

Many Thanks If you tell me any idea you have about this problem.

**Comment by steveheinsch** [comment]
@vah7id Your "message" didn't show up.

**Comment by vah7id** [comment]
@steveheinsch Sry my mistake.
the message is "Unauthorized Query"

**Comment by steveheinsch** [comment]
Do the credentials that you're using to login work on http://retsmd.com? Unauthorized means either your credentials are wrong, or you don't have the proper permissions to access something on the rets server that you're querying. I don't see you querying...just logging in. I'd try:
1) See if you can log in using your credential on retsmd.com
2) Contact the MLS and see if there is a permission issue with your credentials

**Comment by troydavisson** [comment]
Like @steveheinsch said, Unauthorized Query is usually you trying to query a field or get a field back that you don't have access to.
