### ISSUE TITLE
RETS (20203) Miscellaneous Search Error. Error collecting Join metadata

### ISSUE THREAD

**Issue by user4004** [troydavisson/PHRETS#150]
I am facing with the following issue while i tried to extract data from mls. Getting following error as follows:
"RETS (20203) Miscellaneous Search Error. Error collecting Join metadata"
 What should be the reason ? How can i resolve this issue?

**Comment by troydavisson** [comment]
This sounds like an error on the server side, so other than contacting the provider of your RETS access, there likely isn't anything you can do.
