### ISSUE TITLE
Has anyone considered using Mongo?

### ISSUE THREAD

**Issue by Jscott388** [troydavisson/PHRETS#152]
I know this is PHP / SQL. I have been developing something for Node/Express/MongoDB. Has anyone took this route?

**Comment by troydavisson** [comment]
I know a number of users who take data from a RETS server and import it into Mongo.  There shouldn't be anything specifically with this library that wouldn't make that possible, and using some of the `toArray()` methods may help streamline it.

I'd suggest joining our Slack channel (http://phrets.troda.com) to further discuss implementation ideas.
