### ISSUE TITLE
PHP warning:  Node no longer exists

### ISSUE THREAD

**Issue by acmwallace** [troydavisson/PHRETS#154]
In retrieving photos from the MIAMI Association of REALTORS (RETS server: http://sef.rets.interealty.com), I am getting a number of PHP warnings each time I try to get the metadata:

PHP Warning:  PHRETS\Parsers\GetMetadata\System::parse(): Node no longer exists in /home/httpd/vendor/troydavisson/phrets/src/Parsers/GetMetadata/System.php on line 26

(also, line 29 and 32)

It seems to be getting the photos ok, just printing these messages each time I call.

**Comment by troydavisson** [comment]
This suggests that you're trying to interact with the server using a version of RETS it doesn't fully support.  See https://github.com/troydavisson/PHRETS/pull/153 for another example and a bit more of the background.

**Comment by acmwallace** [comment]
thanks, I'll check it out!


--
IHOUSEWEB Inc.
8950 Cal Center Dr
bldg. 1 suite 202
Sacramento, CA 95826

Andy Wallace | Senior Software Engineer | 916-246-7777 |
awallace@ihouseweb.com
