### ISSUE TITLE
get FALSE result when calling the method of SearchQuery

### ISSUE THREAD

**Issue by wangdebin** [troydavisson/PHRETS#155]
the code like this and the server is connected:
$search = $rets->SearchQuery("Property","RES","(ListDate=1990-01-01+)");
but FALSE returned.
I don't know why.

**Comment by troydavisson** [comment]
Since you're using 1.x, in those instances, try:

```
var_dump($rets->Error());
```

when you see that `$search` is false.  That should print out the error information.

**Comment by wangdebin** [comment]
Thanks for replying.
I tried 
var_dump($rets->Error());
and the error information still shows "bool(false)"

**Comment by troydavisson** [comment]
If you enable debug mode using something like:

```
$rets->SetParam("debug_mode", true);
$rets->SetParam("debug_file", "debug_log.txt");
```

I'm interested in seeing the contents of that file after a single complete run of your process.  Feel free to email it to me privately.

**Comment by wangdebin** [comment]
Sure, thanks for you kind patience

**Comment by wangdebin** [comment]
The result of printing is：
 array(3) {
      ["type"]=>
          string(4) "rets"
      ["code"]=>
          string(5) "20207"
      ["text"]=>
          string(18) "Unauthorized Query"
}
I don't understand why "Unauthorized Query"

**Comment by troydavisson** [comment]
That error suggests that there is an issue with the query you're issuing, most likely that `ListDate` either isn't a valid field or it isn't a field you're allowed to search on.
