### ISSUE TITLE
If I want pictures of real estate, do I use the getObjec () method?. Or in this Media resource?

### ISSUE THREAD

**Issue by wangdebin** [troydavisson/PHRETS#156]
hello sir !!!
     GetObject($resource, $type, $id, $photo_number = '*', $location = 0)
     I found the method because I wanted to get the picture, but I didn't understand 
      What does this $id mean? Where does it comes from?

**Comment by steveheinsch** [comment]
Its the id of the resource (ie property - mls id) that you want to retrieve the images for (or other resources like PDF)

**Comment by wangdebin** [comment]
Thank you for your answer!!!

  $rets_modtimestamp_field = "ModificationTimestamp";$previous_start_time = "2010-00-31T00:00:00"; $query = "({$rets_modtimestamp_field}={$previous_start_time}+)";$search = $rets->SearchQuery("Property", 'Residential', $query, array('Limit' => $limit, 'Offset' => $offset, 'Format' => 'COMPACT-DECODED', 'Count' => 1)); 

I've got the information about this house, but I want to get the picture of the house. How can I get the picture of this house? This method is getObjec (GetObject ($resource, $type, $id, $photo_number = *, $location = 0)), there is no house property in the house information inside the ID, or through other ways to obtain, if it is to obtain the other way, can you tell me

**Comment by troydavisson** [comment]
I'd recommend joining our Slack channel (http://phrets.troda.com/) for this type of assistance.  Closing issue as this isn't a software bug with the library.
