### ISSUE TITLE
GetObject($resource, $type, $id, $photo_number = '*', $location = 0) I found the method because I wanted to get the picture, but I didn't understand What does this $id mean? Where does it comes from?

### ISSUE THREAD

**Issue by wangdebin** [troydavisson/PHRETS#157]

**Comment by tspencer9303** [comment]
$id would be the key field for the type you're looking for. If you're on retsmd, and you click on the resource type, the primary key will be listed at the top.

**Comment by troydavisson** [comment]
Not an issue with the software.  I'd recommend joining our Slack group for help from the community: http://phrets.troda.com/
