### ISSUE TITLE
use phrets2.3,but i have only get : Uncaught exception 'PHRETS\Exceptions\RETSException' with message 'Unauthorized Query

### ISSUE THREAD

**Issue by Even-Gao** [troydavisson/PHRETS#162]
How to get the data you want, how to fill in the parameters, I now use the method of readme.md, I don't know how to change the parameters.

**Comment by steveheinsch** [comment]
You have to use the field names from your actual rets server. Most name things differently. One place to check what resources/classes/fields you have access to is http://retsmd.com. You'll need to use your rets credentials so it can access it.

You can also use phrets to get the Resource names, and the Classes that belong to those resources. That's what retsmd.com is doing behind the scenes.

**Comment by Even-Gao** [comment]
ok, i will try again. 
thank you very much, you are so warm-hearted. 
maybe i will need your help later. please keep watching this question. because  i really need your help. 
i have doing this for a long time.

**Comment by Even-Gao** [comment]
<pre><code>
<?php
date_default_timezone_set('America/New_York');
require_once("vendor/autoload.php");
$config = new \PHRETS\Configuration;
$config->setLoginUrl('https://pt.rets.crmls.org/contact/rets/login')
       ->setUsername('xxxxxx')->setPassword('xxxxxx')->setRetsVersion('1.7.2');
$rets = new \PHRETS\Session($config);
$connect = $rets->Login();
$system = $rets->GetSystemMetadata();
$resources = $system->getResources();
$classes = $resources->first()->getClasses();
$classes = $rets->GetClassesMetadata('Property');
var_dump($classes->first());
$objects = $rets->GetObject('Property', 'Photo', '00-1669', '*', 1);
var_dump($objects);
$fields = $rets->GetTableMetadata('Property', 'A');
var_dump($fields[0]);
$results = $rets->Search('Property', 'A', '*', ['Limit' => 3, 'Select' => 'LIST_1,LIST_105,LIST_15,LIST_22,LIST_87,LIST_133,LIST_134']);
foreach ($results as $r) {
    var_dump($r);
}
</pre></code>
this is my code, when i use the function GetObject, i don t no what the params should be, i have already checked http://retsmd.com. but its too many params and i dont no which one should i choose.
could you please give me a example how to use this??
it will be very helpful for me. thank you again.

**Comment by troydavisson** [comment]
Closing since this isn't an issue with the code itself.  Anyone seeking help or deeper understanding of what needs to happen should join our PHRETS Slack community group at http://phrets.troda.com
