### ISSUE TITLE
how to get data or photo use phrets2.3

### ISSUE THREAD

**Issue by Even-Gao** [troydavisson/PHRETS#163]
use phrets1.x that i can get cvs data, but couldn t get photo information.
when use phrets2.3 that i can only get an error like this:"Uncaught exception 'PHRETS\Exceptions\RETSException' with message 'Unauthorized Query' in D:\wamp64\www\PHR\PHRETS-2.3\src\Session.php on line 359";
anyone can help me please, thank you anyway.
<pre><code>
setLoginUrl('https://pt.rets.crmls.org/contact/rets/login')
       ->setUsername('xxxxxx')->setPassword('xxxxxx')->setRetsVersion('1.7.2');
$rets = new \PHRETS\Session($config);
$connect = $rets->Login();
$system = $rets->GetSystemMetadata();
$resources = $system->getResources();
$classes = $resources->first()->getClasses();
$classes = $rets->GetClassesMetadata('Property');
var_dump($classes->first());
$objects = $rets->GetObject('Property', 'Photo', '00-1669', '*', 1);
var_dump($objects);
$fields = $rets->GetTableMetadata('Property', 'A');
var_dump($fields[0]);
$results = $rets->Search('Property', 'A', '*', ['Limit' => 3, 'Select' => 'LIST_1,LIST_105,LIST_15,LIST_22,LIST_87,LIST_133,LIST_134']);
foreach ($results as $r) {
    var_dump($r);
}
</pre></code>

**Comment by troydavisson** [comment]
The server you're connecting to doesn't have fields in the format you're requesting.  You'll need to modify your request to properly ask for fields that server recognizes.

I'd suggest looking at the available fields using retsmd.com and modifying your requests to match that.  If you need further guidance on this, I'd recommend joining our Slack group (http://phrets.troda.com) for some help from the community.
