### ISSUE TITLE
RETS M.D1.5 OR RETS M.D1.7.2

### ISSUE THREAD

**Issue by Even-Gao** [troydavisson/PHRETS#164]
when i login in retsmd.com, the rets version is 1.5, but phrets2.3 use rets version is 1.7.2, whether it has any influence, if you know it , please tell me . thank you anyway.
my Email is 'even@senseluxury.com'， email me.

**Comment by troydavisson** [comment]
retsmd.com and PHRETS are capable of the same versions of RETS.  You declare which version you're using when you establish the connection with the server.
