### ISSUE TITLE
Why does mdiaurl have only one picture

### ISSUE THREAD

**Issue by 1014825794** [troydavisson/PHRETS#169]
In fact, we have to get to the media related information, those fields all you say yes, why this single link mediauel de address only one,
 I need to get all the listings information picture, how can I get all the picture information, 
 so I hope you can help me, thank you very much !!! 
The picture is at the bottom,There is only one picture of URL,This is not what I want;
I did it this way：
                $search = $rets->SearchQuery("Media", $class, $query, array('Limit' => $limit, 'Offset' => $offset, 'Format' => 'COMPACT-DECODED', 'Count' => 1));

                if ($rets->NumRows() > 0) {
                        if ($offset == 1) {
                                // print filename headers as first line
                                $fields_order = $rets->SearchGetFields($search);
                                fputcsv($fh, $fields_order);
                        }
                        // process results
                  // process results
                        while ($record = $rets->FetchRow($search)) {
                                $this_record = array();
                                foreach ($fields_order as $fo) {
    
                                        $this_record[] = $record[$fo];
                                }
                                exit;
                                fputcsv($fh, $this_record);
                        }

                        $offset = ($offset + $rets->NumRows());
                }

But I can get all the pictures through this direct access：

  https://pt.rets.crmls.org/contact/rets/search?SearchType=Media&Class=Media&Count=1&Format=COMPACT-DECODED&Query=(ResourceRecordKeyNumeric=171489074)&QueryType=DMQL2&StandardNames=0&Select=MediaURL
   the result is:
    <?xml version="1.0"?>
<RETS ReplyText="Operation Successful" ReplyCode="0"><COUNT Records="33"/><DELIMITER value="09"/><COLUMNS> MediaURL </COLUMNS><DATA> http://media.crmls.org/medias/ebf96638-7b7b-427a-bf4d-000002b29270.jpg </DATA><DATA> http://media.crmls.org/medias/39ebe417-48da-439c-a2bb-0444b92eb91c.jpg </DATA><DATA> http://media.crmls.org/medias/4c32f52b-2c5c-40f8-aae0-053ebb3b7178.jpg </DATA><DATA> http://media.crmls.org/medias/a99bd552-5b15-423d-960c-082d43837adb.jpg </DATA><DATA> http://media.crmls.org/medias/85c9b922-7a3f-45fe-ade9-11695c530991.jpg </DATA><DATA> http://media.crmls.org/medias/8c158d70-8600-4a60-84cf-226901ee9bed.jpg </DATA><DATA> http://media.crmls.org/medias/28197061-48c4-4f32-934b-26c4a9beb420.jpg </DATA><DATA> http://media.crmls.org/medias/c0e88213-73c0-4d57-9579-28fd9cdafe86.jpg </DATA><DATA> http://media.crmls.org/medias/4cbaefdf-7265-4c48-b592-29e1a985a4ba.jpg </DATA><DATA> http://media.crmls.org/medias/aa016f69-acdb-43de-ba38-2c50b057a82f.jpg </DATA><DATA> http://media.crmls.org/medias/cecf1ed6-5be6-40e4-b156-2c63d293c919.jpg </DATA><DATA> http://media.crmls.org/medias/595280bd-6fe6-4c03-becb-36419788e908.jpg </DATA><DATA> http://media.crmls.org/medias/a6d8852b-3533-4069-ab42-4ad3cf4dda77.jpg </DATA><DATA> http://media.crmls.org/medias/9a8be629-4315-4828-aeed-5b5c7878b3b8.jpg </DATA><DATA> http://media.crmls.org/medias/bde91797-e781-48fc-a862-69935544fb27.jpg </DATA><DATA> http://media.crmls.org/medias/3c16e281-2630-45e6-816b-7391a4e6b9fc.jpg </DATA><DATA> http://media.crmls.org/medias/bb9af381-b9ea-48fd-95dc-7d1da78fd116.jpg </DATA><DATA> http://media.crmls.org/medias/9ff88b04-f8e3-4fb1-a454-8475120c5341.jpg </DATA><DATA> http://media.crmls.org/medias/72792ecc-7830-45de-b3ac-8583346df6e4.jpg </DATA><DATA> http://media.crmls.org/medias/492e3414-4083-4205-b2f7-8a1476c9dc63.jpg </DATA><DATA> http://media.crmls.org/medias/d9018179-da18-4fb5-8cb9-8e5979edda4e.jpg </DATA><DATA> http://media.crmls.org/medias/7eb798a6-83b3-4fc0-ac93-b0198672ada3.jpg </DATA><DATA> http://media.crmls.org/medias/c2dff231-2e5f-434d-9873-b2af401a7b2a.jpg </DATA><DATA> http://media.crmls.org/medias/554c1d0c-11a6-4930-9f4a-b3197586fb37.jpg </DATA><DATA> http://media.crmls.org/medias/8298e954-adf2-4bd3-8de0-b633ea63b075.jpg </DATA><DATA> http://media.crmls.org/medias/50b66c46-9596-49f1-a69d-c78b40aaa35a.jpg </DATA><DATA> http://media.crmls.org/medias/55c8a875-329f-4165-8890-c973a92a77cb.jpg </DATA><DATA> http://media.crmls.org/medias/2052abdf-1632-4310-b522-cf3a273715dd.jpg </DATA><DATA> http://media.crmls.org/medias/20baca9e-8036-4bb8-8698-de9913238e8d.jpg </DATA><DATA> http://media.crmls.org/medias/b41176fe-042c-400b-a1db-e929f16db9ca.jpg </DATA><DATA> http://media.crmls.org/medias/5bc9844b-3496-42fe-aed6-faa7e6037768.jpg </DATA><DATA> http://media.crmls.org/medias/55a8ef2e-f7ce-4c67-bd67-fc793db9b71a.jpg </DATA><DATA> http://media.crmls.org/medias/ecd85adb-6350-4057-8e55-fd19abdc69a4.jpg </DATA></RETS>

![image](https://user-images.githubusercontent.com/25998544/30410014-191c6570-993b-11e7-9067-26a650958d29.png)

**Comment by steveheinsch** [comment]
Why do you have an `exit` in your while loop?

What version of PHRETS are you using? Some of that code appears to be from version 1.

As a side note, github `issues` isn't really the place for technical help. It's for reporting bugs in the PHRETS software, and this doesn't seem to be related to a bug.

**Comment by troydavisson** [comment]
As @steveheinsch suggested, our Slack group (http://phrets.troda.com/) is probably the best place for this kind of assistance.  This isn't a bug with PHRETS directly.
