### ISSUE TITLE
Unable to Login with Corelogic Matrix-RETS

### ISSUE THREAD

**Issue by Aeyzaz** [troydavisson/PHRETS#177]
Hello,

I am unable to login, tried every possible solution on the internet. i can login using retsmd.com and retsmd.com/auth but with the same details i cannot login through PHRETS 2.0.

I have tried to set the cookies file using
```
$rets->getClient()->setDefaultOption('config', [
    'curl' => [
        CURLOPT_COOKIEFILE => tempnam('/tmp', 'phrets')
    ]
]);
```

but it throws exception:
Fatal error: Uncaught exception 'RuntimeException' with message 'Error creating resource: [message] fopen(config): failed to open stream: No such file or directory

Any Help will be appreciated.

**Comment by Aeyzaz** [comment]
Anyone who has the same issue please check your PHP Configurations and enable curl_exec functions. in my case this was the problem because the hosting provider upgraded my server and disabled some functions. Thanks!

**Comment by hone5t** [comment]
@Aeyzaz where you able to get a result with search
every query I do ended up without result without getting any error

**Comment by Aeyzaz** [comment]
@hone5t what is that error that you are getting?
