### ISSUE TITLE
Conection issue on live server

### ISSUE THREAD

**Issue by sourabhgarg01** [troydavisson/PHRETS#19]
When I used to connect phrets on my local server it works perfectly.
But when I used it to connect on Live server the connection is not established.

In debug file I got msg:-
- About to connect() to rets.torontomls.net port 6103 (#0)
-   Trying 68.71.195.47... \* Connection timed out
- couldn't connect to host
- Closing connection #0

//Code is as follows:-

$rets = new phRETS;
$rets->AddHeader("RETS-Version", "RETS/1.5");
$rets->SetParam("debug_mode", true);
$rets->SetParam("disable_follow_location", true);
echo "+ Connecting to {$rets_login_url} as {$rets_username}<br>\n";
$connect = $rets->Connect($rets_login_url, $rets_username, $rets_password);
if ($connect) {
        echo "  + Connected<br>\n";
}
else {
        echo "  + Not connected:<br>\n";
        print_r($rets->Error());
        exit;
}

Please help me..  what are the possibilities may occer..

**Comment by Thavaraja** [comment]
Hi 

I got error 

* Uses proxy env variable no_proxy == '1'
*   Trying 206.152.41.137:6103...
* connect to 206.152.41.137 port 6103 failed: Connection refused
* Failed to connect to rets.torontomls.net port 6103: Connection refused
* Closing connection 0

I can't upload the images 
I asked hosting provider they said port 6103 is open, Do you know how to solve this
