### ISSUE TITLE
Call to undefined method phRETS::GetSystemMetadata()

### ISSUE THREAD

**Issue by JohnsonMikeJ** [troydavisson/PHRETS#192]
While trying to use the sample code listed at https://github.com/troydavisson/PHRETS/wiki/Create-mysql-tables-from-rets-metadata - the GetSystemMetadata doesn't exist (1.x version)

Is this an oversight or is that sample for a different version of phRETS?

**Comment by saurabhsinghthakur** [comment]
Call to undefined method phRETS::GetSystemMetadata()

**Comment by troydavisson** [comment]
That example is for an older version of this library (see the first note on the page you linked).  That said, the method names aren't much different with the newest version so it wouldn't take much to adapt it.
