### ISSUE TITLE
Cannot use PHRETS\Models\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by docmattman** [troydavisson/PHRETS#197]
`In Single.php line 4:`
`Cannot use PHRETS\Models\Object as Object because 'Object' is a special class name`

Since `Object` is a reserved word, shouldn't the class be renamed to something else?

**Comment by troydavisson** [comment]
https://github.com/troydavisson/PHRETS/pull/179 addressed this but it hasn't been released yet.
