### ISSUE TITLE
Object Class needs renamed for PHP 7.2 compatibility

### ISSUE THREAD

**Issue by irishhawk23** [troydavisson/PHRETS#199]
PHP 7.2 and on will no longer allow classes to be named object so the object class has to be renamed. 

production.ERROR: Cannot use PHRETS\Models\Object as Object because 'Object' is a special class name {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Cannot use PHRETS\\Models\\Object as Object because 'Object' is a special class name at /home/forge/atthecoastrealestate.com/vendor/troydavisson/phrets/src/Parsers/GetObject/Single.php:4)

Cheers,

**Comment by brettneville** [comment]
@irishhawk23 - I see you marked this closed a couple of weeks ago. I'm running into the same issue, trying to run PHRETS on php 7.2.  where I get an error on the following file: 
/vendor/troydavisson/phrets/src/Parsers/GetObject/Single.php:4
