### ISSUE TITLE
PHP Fatal error:  Cannot use PHRETS\Models\Object as Object because 'Object' is a special class name in src/Parsers/GetObject/Single.php on line 4

### ISSUE THREAD

**Issue by twheel** [troydavisson/PHRETS#200]
PHP 7.2

**Comment by steveheinsch** [comment]
Have you updated? That was fixed about 3 months ago here: https://github.com/troydavisson/PHRETS/pull/179

**Comment by twheel** [comment]
I updated via composer.  Is there a better way?

**Comment by steveheinsch** [comment]
Oh, it looks like @troydavisson hasn't put it into a release yet. I think it's only in the master branch.

**Comment by twheel** [comment]
OK, thanks.  I'll download from here.
