### ISSUE TITLE
Won't run with PHP 7?

### ISSUE THREAD

**Issue by uudruid74** [troydavisson/PHRETS#201]
PHP Fatal error:  Cannot use PHRETS\Models\Object as Object because 'Object' is a special class name in /var/www/eddon.systems/htdocs/teel-waters/vendor/troydavisson/phrets/src/Parsers/GetObject/Single.php on line 4

Using PHP 7.2.2

Edit: Also .. see here ... seems to be a duplicate of an issue other projects have with 7.2
https://github.com/unclead/yii2-multiple-input/issues/177

**Comment by steveheinsch** [comment]
@uudruid74 It has been discussed and fixed in this commit: https://github.com/troydavisson/PHRETS/pull/179

It's in the master branch, but hasn't been made into a release yet.

**Comment by steveheinsch** [comment]
@uudruid74 I got notified of your edit, but as I mentioned, it's already fixed in the master branch.

**Comment by troydavisson** [comment]
2.6 was released this evening with this change, so PHP 7.2+ should work as expected now once you update w/ Composer.
