### ISSUE TITLE
Want to install manually, without composer

### ISSUE THREAD

**Issue by nonny2019** [troydavisson/PHRETS#223]
Hi,

I am new to PHRets and want to install PHRets manually, without using composer. 
Please, help me how I can install it and where.

Thanks

**Comment by steveheinsch** [comment]
That won't be easy, as PHRETS has other dependencies, and those dependencies have other dependencies, and so it goes. You'd have to find every single package and manually install them. It's not impossible, but will take quite a bit of time. This isn't unique to phrets, so you should search for more general advice like https://stackoverflow.com/questions/40545795/how-do-i-install-composer-php-packages-without-composer

Personally, I'd stick with composer. Life is so much easier with it.
