### ISSUE TITLE
CoreLogic Trestle

### ISSUE THREAD

**Issue by hone5t** [troydavisson/PHRETS#231]
anyone have an issue with phprets not returning results when using search for property

` $searchProperty = $rets->Search('Property', "Property", "*", [
'Limit' => 3,, 'Select' => 'MlsStatus'
 ])->toArray();  `
`        foreach ($searchProperty as $record) {
            exit(var_dump($record));
        }`
i also tried
` $searchProperty = $rets->Search('Property', "Property", "(ListingKey=0+)", [
'Limit' => 3,, 'Select' => 'MlsStatus'
 ])->toArray();  `
`        foreach ($searchProperty as $record) {
            exit(var_dump($record));
        }`

<img width="706" alt="Screen Shot 2019-04-12 at 7 55 03 PM" src="https://user-images.githubusercontent.com/960415/56072486-017fb880-5d5d-11e9-8e5d-db563986e18c.png">

I don't get any records but I can get media objects  which tell me that the library work with the feed there is just something I am missing
I thought maybe the search is not supported but as you can see below its actually supported
<img width="727" alt="Screen Shot 2019-04-12 at 7 59 38 PM" src="https://user-images.githubusercontent.com/960415/56072522-8b2f8600-5d5d-11e9-8b3b-3a6ff04d6ac1.png">

anyone have the same issue or have a solution
Thanks!

**Comment by bfjare** [comment]
I'm having the same issue with CoreLogic Trestles new API.

**Comment by hone5t** [comment]
@bfjare 
I figure it out
you can't do the search without query and the listing id I suspect it's stored as string that's why the + doesn't work on it.
here is a working example
` 
$results = $rets->Search('Property', 'Property', '(ModificationTimestamp=2019-04-11T00:00:00+)', ['Limit' => 3])->toArray();
`
let me know if you still have any issue with getting it to work.

**Comment by bfjare** [comment]
Yep this is working for me.
