### ISSUE TITLE
Unexpected end of Query on \PHRETS\library\src\Session.php:424

### ISSUE THREAD

**Issue by AkramChauhan** [troydavisson/PHRETS#232]
`$results = $rets->Search('Property','RE_1','*', ['Limit' => 1]);
foreach ($results as $r) {
	echo $r;
}`

When keeping * in query it says Unexpected end of Query.
I just want all property in desc order by limit.

Need One more advise if possible.
Should I display RETS data directly to Website or 
Should I store in Mysql and than display in Website.
and If I store in Mysql What Should I do for Keep it updated.

Thank you.

**Comment by troydavisson** [comment]
I believe the * query only works on Flexmls RETS servers.  If RE_1 is the
correct class name, I'd suggest trying the following instead to get some
records:

(L_ListingID=0+)

**Comment by AkramChauhan** [comment]
Thanks for quick response.
That worked for me.
