### ISSUE TITLE
What should be best practice to use this Library

### ISSUE THREAD

**Issue by AkramChauhan** [troydavisson/PHRETS#233]
Hi @troydavisson , I was facing difficulties while developing API for one MLS.
Can you guide me to build standard practice to use RETS.

Like what should be preffered method to communicate with RETS data.
Here is what I'm thinking possible ways to do this.
1) Keeping it real time. when user enter keyword at that time perform search query directly from RETS.
2) Storing all MLS Property in MYSQL database and serving data from MYSQL to website.

In case 2:
What should be standard way to sync data and keep updated previous data.

For example if any MLS is having 30K properties.
Should I import 30K property on daily basis? In order to keep it updated?

Please guide me on this.

Thanks in advance. :)

**Comment by troydavisson** [comment]
You'll need to substitute some field names if the server you're accessing isn't the Flexmls RETS server, but I believe https://www.flexmls.com/developers/rets/tutorials/how-to-efficiently-replicate-rets-data/ should answer at least most of your questions.

**Comment by AkramChauhan** [comment]
That's what I was looking for.
Thanks @troydavisson .
