### ISSUE TITLE
GetObject Error Invalid Type

### ISSUE THREAD

**Issue by clustersolutions** [troydavisson/PHRETS#249]
When I call the CRMLS GetObject method below I kept getting invalid type error for the Porperty resource. Can anyone please help? Could it be a privilege? Also, is there a way to check what object types are available from the CRMLS for the Property resource?

`$objects = $rets->GetObject('Property', 'Photo', 'SB1922785', '*', 1);`

Thanks so much for your help!

**Comment by clustersolutions** [comment]
Ah...spent a day on this...may finally found the answer.

https://stackoverflow.com/questions/31020248/how-do-i-get-images-from-the-mls-rets-feed-provided-by-crmls-formerly-carets-ml

**Comment by Joyfred** [comment]
Hey...I looked into the solution. But the image in the URL provided in Media resource is of low resolution. Is there anyway to get high resolution images?
