### ISSUE TITLE
MFRMLS - Too many outstanding queries 

### ISSUE THREAD

**Issue by vikasj-wmt** [troydavisson/PHRETS#253]
We are fetch property from stellar MLS - MFRMLS using PHRETS. Property data is coming proper but we are facing one error like : **Error Code : 20210 & Error Message : "Too many outstanding queries"** & also we are facing other one error => **Error Code : 20022 & Error Message : "Additional login not permitted"** 

We are working with laravel job for fetch property.
we are run my job multiple time - every 5 minutes.  
So please give solution for this error.

Thanks

**Comment by Patfreeze** [comment]
We had this same issue but fixed it by waiting 30sec before reconnect.
The problem we had was because 2 connections was open at the same time.

Hope it will help you.

**Comment by vikasj-wmt** [comment]
Issue is resolved
