### ISSUE TITLE
Search Transaction > Get Long Values

### ISSUE THREAD

**Issue by mehranabi** [troydavisson/PHRETS#259]
Hello everyone,
And thanks for this amazing package.
Currently, when I do Search transaction I get "Short Value" for lookup fields, I'm wondering how can I retrieve "Long Value" for fields. (Is that even possible or should I map the values later by retrieving metadata)

**Comment by troydavisson** [comment]
If you're getting records back with the short values, that suggests that the server is returning the data in COMPACT format.  You're looking for COMPACT-DECODED which can be asked for at the time of the request with the `Format` option.

**Comment by mehranabi** [comment]
Oh I see, I'll check this option out. Thanks @troydavisson !

**Comment by mehranabi** [comment]
Hello Again!
Hope you are healthy and well.

I tested `COMPACT-DECODED` for `Format` option but no chance.
I'm actually getting `Value` of fields, not even `Short Value`. 

My code is:
```
$result = $rets->Search('Property', $class . 'Property', $query, [
    'Select' => $select,
    'Limit' => $limit,
]);
```

* My MLS provider is Toronto Real Estate Board and they are using 1.7 version.
* For example, I get "C." for `Type_own_srch` field! which its Short and Long value is `Condo Apt`
