### ISSUE TITLE
CoreLogic just changed to https instead of http and photos are not coming down

### ISSUE THREAD

**Issue by OahuRE** [troydavisson/PHRETS#265]
CoreLogic just stopped allowing http and now my photos come down as one big .jpg file which can't be viewed instead of separate jpg files.

Is there a way to fix this for users who communicate with CoreLogic.

**Comment by troydavisson** [comment]
The recent changes to Matrix to require TLS 1.2 through HTTPS shouldn't have had any impact on how photos are delivered.  Can you provide more information about what you're seeing?

**Comment by OahuRE** [comment]
Thanks Troy for responding and I should have clarified I was not on the most recent version of PHRETS. I installed the latest and got that working to download the photos again.
