### ISSUE TITLE
Search Record By Address

### ISSUE THREAD

**Issue by Ghostff** [troydavisson/PHRETS#277]
How do I search record by address, I tried this:
```php
$mls->Search('Property', 'RE', "(L_Address=1234 Address St)", [
    'Select' => 'L_Address,L_AddressStree,...t',
    'Limit'  => 1,
])->first(function (Record $record) {
    dd($record);
});
```
But but am not getting a result, event though specified address exists in MLS. I also tried:
```php
$mls->Search('Property', 'RE', "(L_Address=|1234 Address St)", [
    'Select' => 'L_Address,L_AddressStreet,...',
    'Limit'  => 1,
])
```
But get `"Missing equals sign after field name."`

**Comment by rfahey79** [comment]
Depending on your MLS, to search address you'll need multiple fields, i.e. ('L_Number=123,L_StreetName=Address,L_StreetSuffix=St')

**Comment by nader14y** [comment]
Second query is wrong as L_Address is not a lookup field. Better to use (L_Address=*address*), so you can make sure the MLS includes any records for that query.
