### ISSUE TITLE
Need option for download without composer

### ISSUE THREAD

**Issue by nom3d** [troydavisson/PHRETS#280]
I'm using dreamhost and they don't support composer on their basic accounts. It would be great to have a download without composer, can anyone help? 

See this link
https://help.dreamhost.com/hc/en-us/articles/214899037-Installing-Composer-overview

Thank you!

**Comment by bradroberts** [comment]
You could use Composer to install PHRETS on your local computer, then FTP the entire `vendor` directory to your web server. You'll just need to require the autoload file that Composer provides: `require __DIR__ . '/vendor/autoload.php';`. Just make sure the path is correct. You'll likely have a few thousand files in the vendor directory, so this isn't the best solution, but it's likely your only option outside of a more flexible hosting setup.

**Comment by maietta** [comment]
If you hosting provider doesn't offer the features you need, you should be looking for a new hosting provider that can meet the needs of your project. One size does not fit all when it comes to hosting apps and websites.
