### ISSUE TITLE
Can I get the data in a second language?

### ISSUE THREAD

**Issue by omarfandino** [troydavisson/PHRETS#288]
Hi Troy Davisson

Greetings from Colombia! ... Your complement is fantastic (https://github.com/troydavisson/PHRETS), it has helped me a lot. I have a question:

Can I get the data in a second language? … For exaple: When I request “$item['web_title'], i get “For sale in PH Pacific Wind, Tower 2000” instead of “Venta en P.H. Pacific Wind, Torre 2000”

I don’t know how to set this option, Could you help me please? … In MLS there is the English option, but there is also the Spanish option.

Thank you very much, greetings

**Comment by troydavisson** [comment]
RETS only supports options for a single language unless the server has added some additional capabilities (which isn't likely) so you may be stuck translation these on your own with the help of a third party translation API.
