### ISSUE TITLE
Trying to get photos using GetObject strange result

### ISSUE THREAD

**Issue by eggplantstudios** [troydavisson/PHRETS#299]
Hello,

I'm attempting to pull images for a given ListingKey.

```
 $object = $rets->getObject(
                'Property',
                'LargePhoto',
                $listingKey,
                '*',
                1
            );
```

It returns an array with a single PHRETS\Models\BaseObject object, with the content containing an XML list:

```
<rets replycode="0" replytext="Operation Successful">
  <count records="42">
    <delimiter value="09">
      <columns> ResourceRecordID  Order MediaUrl  MediaModificationTimestamp  </columns>
      <data>  12345679  1 https://ddfcdn.realtor.ca/listings/TS637669021840000000/reb12/highres/1/2460991_1.jpg 2021-09-10T20:23:04Z  </data>
      <data>  12345679  2 https://ddfcdn.realtor.ca/listings/TS637669021840000000/reb12/highres/1/2460991_2.jpg 2021-09-10T20:23:04Z  </data>
      <data>  12345679  3 https://ddfcdn.realtor.ca/listings/TS637669021840000000/reb12/highres/1/2460991_3.jpg 2021-09-10T20:23:04Z  </data>
      <data>  12345679  4 https://ddfcdn.realtor.ca/listings/TS637669021840000000/reb12/highres/1/2460991_4.jpg 2021-09-10T20:23:04Z  </data>
    </delimiter>
  </count>
</rets>
```

This isn't exactly what I was expecting. Am I supposed to be digging into this XML to retrieve the URLS I need? Or is there some process I am missing that would have these populated as arrays or objects instead?

**Comment by troydavisson** [comment]
That sounds like a horribly broken RETS server.  That's the underlying format when you get data back for Search(), not GetObject().  I'd half expect to see that in a debugging log if you issued a query to a Media resource, but GetObject doesn't give XML in normal instances.
