### ISSUE TITLE
php 8.x deprecated errors

### ISSUE THREAD

**Issue by thepofo** [troydavisson/PHRETS#303]
Would it be possible to update the code to make it PHP 8.x compatible?

I have the following deprecated error: some examples:

Deprecated: Return type of PHRETS\Models\Search\Results::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Users.......

Thx
Eric

**Comment by jonathanmelville** [comment]
I second this.

**Comment by PAXANDDOS** [comment]
I agree. There is PHP 8.2 coming soon, and some of these deprecations may become warnings or even errors

**Comment by pixelprogrammer** [comment]
In the readme file it says the following PHP versions are supported:
```
PHP 5.6, 7.0, 7.1 and 7.2 supported
```

Would making things compatible with PHP 8+ break things for users still on PHP 5? If so, would it make sense to move this potential update to a 3.0 version and drop PHP 5 support completely?

**Comment by maietta** [comment]
> I agree. There is PHP 8.2 coming soon, and some of these deprecations may become warnings or even errors

Support for 8.2 will never arrive.

**Comment by troydavisson** [comment]
These are addresses in the most recent release.
