### ISSUE TITLE
How do you update PHRETS?

### ISSUE THREAD

**Issue by barkster** [troydavisson/PHRETS#305]
I obviously have an old version on phrets on my servers.  I tried just install with composer per instructions but it didn't seem to update it.  I'm getting error when trying to use freeresult Call to undefined method PHRETS\Session::FreeResults() 

And how do I check what version I even have? Thanks

**Comment by barkster** [comment]
after looking in the configuration file it looks like my update did work, says 2.6.3.  I feel like when I run a query my server bogs down so I was trying to add the freeresult after I loop each set but obviously that is not longer a method.

**Comment by troydavisson** [comment]
It's about as light as it can be.  FreeResult isn't used anymore.  I'm not sure how you're using PHRETS but one option could be defining a lower Limit value in your Search call so it's working with fewer records at a time.
