### ISSUE TITLE
ReplyCode 20203

### ISSUE THREAD

**Issue by Screek1** [troydavisson/PHRETS#307]
Hello, my query look as
`$results = $this->rets->Search('Property', 'RD_1', "*", ['Limit' => null, 'Select' => 'L_ListingID,L_UpdateDate']);`
but me need select only active listings, I try this query
`$results = $this->rets->Search('Property', 'RD_1', "L_Status=Active", ['Limit' => null, 'Select' => 'L_ListingID,L_UpdateDate']);`
and I receive this error 
 ```
PHRETS\Exceptions\RETSException: Could not parse DMQL2 Query: Lookup StatDetail defines no lookup type with value: 'Active' at or near position 11. [...(L_Status= !-->Active)),((] in /Volumes/Code/estateblock/vendor/troydavisson/phrets/src/Session.php:437 
```

How can I get listing by status?

**Comment by troydavisson** [comment]
You'll need to find the correct value for Active.  Using your RETS credentials, log into retsmd.com, select RD_1 and find the L_Status field.  On the right side, click Values and get the value from the leftmost column and use that in your query.

**Comment by roguewdesign** [comment]
I'm getting the same error. I've tried using the Value, Short Value and Long Value but all return the same error.
