### ISSUE TITLE
Running out of memory for HUGE feeds (solved but wanted to share)

### ISSUE THREAD

**Issue by jeleczko** [troydavisson/PHRETS#31]
OK should say I love phrets and use it quite often but for a while when it comes to a very very large feed I always get a "OUT OF MEMORY ERROR"  for months I changed how I parsed the data so it came to phrets as smaller chunks.  BUT today I happen to notice that the error I was getting was with preg_replace and since preg_replace is knows to have memory leaking issues I thought I would look into it.  

turns out not only does pre_replace not like large amounts of data either does the utf8_encode() function 

so line 1535 is:

$data = preg_replace('/&(?!\w+\;)/', '&amp;', $data);

I CHANGED TO:

```
                    //jim start\\
        $myStrLen = strlen($data);
        if ( $myStrLen > 4096 ){
            $howManySplits = $myStrLen/4096;
            $howManySplits = ceil($howManySplits);
            //  echo "\n $myStrLen / $howManySplits \n";
            $l_instr = "";
            for ($i = 0; $i < $howManySplits; $i++) {
                $startchunk = $i*4096;
                $chunk = substr($data,$startchunk,4096);
                $chunk = preg_replace('/\&\s/', '&amp; ', $chunk);
                $l_instr .= $chunk;
                unset($chunk);
            }
            $data = $l_instr;
        }else{
            $data = preg_replace('/\&(?!\w+\;)/', '&amp;', $data);
        }
        //jim end\\
```

on line 1742

$in_str = preg_replace('/&\s/', '&amp; ', $in_str);

I CHANGED TO:

//jim start\
        $myStrLen = strlen($in_str);
        if ( $myStrLen > 4096 ){
            $howManySplits = $myStrLen/4096;
            $howManySplits = ceil($howManySplits);
            //  echo "\n $myStrLen / $howManySplits \n";
            $l_instr = "";
            for ($i = 0; $i < $howManySplits; $i++) {
                $startchunk = $i*4096;
                $chunk = substr($in_str,$startchunk,4096);
                $chunk = preg_replace('/&\s/', '&amp; ', $chunk);
                //  echo "\n $chunk \n";
                if ($cur_encoding == "UTF-8" && mb_check_encoding($in_str, "UTF-8")) { 
                    //return $in_str;
                    $l_instr .= $chunk;
                }else {
                    $l_instr .= utf8_encode($chunk);
                }
                unset($chunk);
            }
            return $l_instr;
        }else{
            $in_str = preg_replace('/&\s/', '&amp; ', $in_str);
            if ($cur_encoding == "UTF-8" && mb_check_encoding($in_str, "UTF-8")) { 
                return $in_str;
            }else{
                return utf8_encode($in_str);
            }
        }
        //jim end\

This all seems to be working for me without the memory issues.  I would suspect others are having a similar issue but have found ways around it.  This seems to be a way not to have to "go around it"

thanks,
Jim 
![phrets1](https://f.cloud.github.com/assets/6163074/1903996/5e1bb630-7c89-11e3-8087-aaaf034f34fb.jpg)
![phrets2](https://f.cloud.github.com/assets/6163074/1903999/61760286-7c89-11e3-9490-9ff2fe762e11.jpg)

**Comment by troydavisson** [comment]
Closing this since it relates to an issue with the old 1.x version.
