### ISSUE TITLE
FLEX MLS starting pulling in all listings including closed

### ISSUE THREAD

**Issue by kristopherlarson** [troydavisson/PHRETS#314]
Randomly my scripted started pulling in all listings that are not active. This includes listings from 10 years ago and now its crashing my script as its pulling in 40,000 listings instead of a 2000. How can I change this query to only grab active listings. I'm trying to add in LIST_15 variable that only pulls listings with status of Active'

$is_active = 'Active';
$listings_query = '(LIST_87=1950-01-01T00:00:00+),(LIST_15='.$is_active.')';

	$results = $rets -> Search(
		'Property',
		$the_class,
		$listings_query,
		[
			'QueryType'     => 'DMQL2',
			'Count'         => 1, // count and records
			'Format'        => 'COMPACT-DECODED',
			'Limit'         => 999999,
			'StandardNames' => 0, // give system names
		]
	)

**Comment by troydavisson** [comment]
If you log into retsmd.com using your RETS credentials, pull up the "A" class under "Property", find LIST_15 in the field list and click "Values" on the right side.  You need the value on the far left when you write the query.  Note that it's a different code for each property type so if you pull more than "A", you'll need to grab the other relevant codes.
