### ISSUE TITLE
Undefined constant "PHRETS\CURLOPT_COOKIEFILE"   at vendor/troydavisson/phrets/src/Session.php

### ISSUE THREAD

**Issue by ManasDas-9801** [troydavisson/PHRETS#315]
Hello all , i am encountering these error message don't know where to start the debugging can anyone suggest

**Comment by ManasDas-9801** [comment]
![image](https://user-images.githubusercontent.com/73233446/220626885-78cf7957-c7bd-4ebc-8a3a-3a59eac15c60.png)

**Comment by gkyle001** [comment]
I am seeing the same error - was there a solution?
