### ISSUE TITLE
Possible improvement: add ability to add arbitrary cURL options

### ISSUE THREAD

**Issue by curquhart** [troydavisson/PHRETS#34]
I thought of a significantly better way to deal with https://github.com/troydavisson/PHRETS/pull/33 (sorry I should have created an issue before I sent a pull request)... I'll change the pull request and re-open it if you like this idea:

Could we make $ch protected so we can override RETSQuery and access $ch directly via a subclass?

**Comment by troydavisson** [comment]
With 2.x, the ability exists to retrieve the underlying Guzzle client which allows you to manipulate it in a huge number of ways.
