### ISSUE TITLE
Error When trying to activate

### ISSUE THREAD

**Issue by cpollinger** [troydavisson/PHRETS#42]
Notice: Undefined index: scheme in phRETS->Connect() (line 1370 of /homepages/2/d179335834/htdocs/RyenBE/sites/all/libraries/phrets/phrets.php).
Notice: Undefined index: scheme in phRETS->Connect() (line 1371 of /homepages/2/d179335834/htdocs/RyenBE/sites/all/libraries/phrets/phrets.php).
drealty encountered an error: (Type: http Code: 0 Msg: )

Help?

**Comment by doggerman** [comment]
Trying to get data using dreality. The error I get is "**dreality encountered an error" (Type: http Code: 0 Msg: ) Disconnected from RETS server. No items to process. exiting**".
I am using drush to import the data. But this is not working.
