### ISSUE TITLE
SQL Tables

### ISSUE THREAD

**Issue by Aeyzaz** [troydavisson/PHRETS#51]
Hello, Create_tables_from_sql is not completely replicating the fields. Most of the fields are missing which cause values to be mismatch.

**Comment by TheDigitalOrchard** [comment]
@Aeyzaz are you referring to the function provided to automatically create MySQL tables from RETS Metadata? That code worked flawlessly for me. I did enhance and tweak it slightly, but only for my own business needs.

Can you elaborate on example what you are doing, and what results you are getting?

**Comment by Aeyzaz** [comment]
Hello, I fixed that issues with GetMetaData method. Thanks for support
