### ISSUE TITLE
correct  username and password but Cannot  login

### ISSUE THREAD

**Issue by karthikphrets** [troydavisson/PHRETS#58]
$login = 'https://rets-stage-paragon.sandicor.com/rets/fnisrets.aspx/sandicor/login';
$un = '********';
$pw = '********';
<?php

/* Initialize Object */
$rets = new PHRETS;

/* Connect */
$connect = $rets->Connect($login, $un, $pw);
$rets->FirewallTest();
/* Query Server */
if($connect) {
	$types = $rets->GetMetadataTypes();
	print_r($types);
	$rets->Disconnect();
} else {
	$error = $rets->Error();
	print_r($error);
}

?>

Output:
--------
Firewall Test: google.com:80 GOOD

Firewall Test: demo.crt.realtors.org:80 FAILED

Firewall Test: demo.crt.realtors.org:6103 FAILED

Firewall Test: retsgw.flexmls.com:80 GOOD

Firewall Test: retsgw.flexmls.com:6103 GOOD

Firewall Result: At least one port 6103 test passed.  Likely cause: One of the test servers might be down but connections on port 80 and port 6103 should work.Array
(
    [type] => http
    [code] => 0
    [text] => 
)

**Comment by metalcro** [comment]
I had a similar problem. Try changing your rets version and/or adding your user-agent header into the code.

**Comment by troydavisson** [comment]
The demo CRT server is no longer available, so the test output you included is showing that the connections on those ports are fine (if you exclude the server that no longer exists).
