### ISSUE TITLE
 PHRETS with cakephp integration 

### ISSUE THREAD

**Issue by karthikphrets** [troydavisson/PHRETS#59]
I'm able to install the PHRETS library files in the vendor folder in the cakephp 3.0. When made a login call, it gives the response as

Client error response [url] https://rets-stage-paragon.sandicor.com/rets/fnisrets.aspx/SANDICOR/login [status code] 401 [reason phrase] Invalid Username/Password combination

But when I directly call the login url from the browser, it login successfully.

Please do the needful. Thanks.

**Comment by troydavisson** [comment]
More appropriate for the mailing list (which you've already posted on).
