### ISSUE TITLE
Documentation deprecated

### ISSUE THREAD

**Issue by danielrvt** [troydavisson/PHRETS#60]
Been trying to follow examples in the wiki, but a lot of functions are undefined. Is this because the documentation isn't up to date or are they ok and it's just me doing all the wrong way?

**Comment by tashworth19191** [comment]
yeah,  I having the same problem trying to figure out syntax stuff for
2.0....

On Tue, Apr 21, 2015 at 4:37 PM, Daniel Rodriguez del Villar Trimarchi <
notifications@github.com> wrote:

> Been trying to follow examples in the wiki, but a lot of functions are
> undefined. Is this because the documentation isn't up to date or are they
> ok and it's just me doing all the wrong way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/troydavisson/PHRETS/issues/60>.
>



-- 


[image: Email Ideas eCard] <http://1unv.com/fcwsg0/c.map>

**Comment by troydavisson** [comment]
Most of the wiki documentation doesn't apply to version 2 of PHRETS.
The README
file <https://github.com/troydavisson/PHRETS/blob/master/README.md>
contains the bulk of the documentation for version 2 at this point.

**Comment by troydavisson** [comment]
I've added a heading to nearly all wiki pages to now indicate that it's basically deprecated and only applies to the original 1.x version.
