### ISSUE TITLE
PHRETS with cakephp

### ISSUE THREAD

**Issue by karthikphrets** [troydavisson/PHRETS#61]
Client error response [url] https://rets-stage-paragon.sandicor.com/rets/fnisrets.aspx/SANDICOR/login [status code] 401 [reason phrase] Invalid Username/Password combination
 when I directly call the login url from the browser, it login successfully.

Some times it shows this type Error
RETS ReplyCode="20036" ReplyText="miscellaneous server error.RETS
 When url run in browser or using PHRETS plugin

Could You send any demo url means, it is very usefully to check the  PHRETS plugin

**Comment by troydavisson** [comment]
Try the new methods added in the newest version (2.1).  You can see the documentation updates here:

https://github.com/troydavisson/PHRETS/commit/06fc6b8f4854a6dff784b71ecec121301077dd6b

This server might require that you use Basic authentication instead of Digest.
