### ISSUE TITLE
RETS Server: Invalid field (null) in query parameter.

### ISSUE THREAD

**Issue by gbrock** [troydavisson/PHRETS#66]
Encountered this error when querying anything but `*` for Properties:

```
RETS Server: Invalid field (null) in query parameter. . See: https://www.flexmls.com/rets/e/27
```

Unfortunately, https://www.flexmls.com/rets/e/27 is a dead link.

[The URL running the query.](http://retsgw.flexmls.com:80/rets2_1/Search?SearchType=Property&Class=A&Query=%28chattanooga%29&QueryType=DMQL2&Count=1&Format=STANDARD-XML&Limit=10&StandardNames=0&Select=LIST_1%2CLIST_105%2CLIST_15%2CLIST_22%2CLIST_87%2CLIST_133%2CLIST_134)

Querying `*` returns results successfully.  I'm happy to submit any additional information that may help troubleshoot this.

**Comment by troydavisson** [comment]
DMQL requires that you provide the field and value as part of the query.  Simply having your query set to ```(chattanooga)``` isn't going to be enough.

The Flexmls RETS server does support the ```*``` query to return all results available to your credentials, but anything other than will require both a field and value.
