### ISSUE TITLE
PHRETS issue/question: Using PHP to download real estate listing photos

### ISSUE THREAD

**Issue by r-interactive** [troydavisson/PHRETS#67]
When using PHP to download real estate listing photos to the server, does it automatically update or replace the old/current photo with the new photo from the MLS to my server. 
If it does, it's not working for me. 

my current code to grab the listing photos to my server:

	if($rets->TotalRecordsFound() > 0) {
		while($data = $rets->FetchRow($search)) {

			$listing_id = $data['sysid'];
			$n = 1;
			
			$photos = $rets->GetObject('Property', 'Photo', $listing_id);
			
			foreach($photos as $photo) {
				if ($photo['Success'] == true) {
					file_put_contents('photos/'.$listing_id.'-'.$n.'.jpg', $photo['Data']);
				}
				$n++;
			}
			$rets->FreeResult($photos);			
		}
		echo "Collected All data successfully";
	} else {
		echo '0 Records Found';
	}

**Comment by troydavisson** [comment]
The desire you've expressed is outside of the scope of what PHRETS does.  PHRETS gives you a way to implement that kind of functionality within your own code (by making it easier to make requests to a RETS server), but it doesn't do it for you.
