### ISSUE TITLE
PHRETS issue: downloading all photos from all property classes

### ISSUE THREAD

**Issue by r-interactive** [troydavisson/PHRETS#68]
I am having trouble pulling all photos from all the property classes (Commercial, Residential, Rental, Lots and Land, open houses & Cross Property) to the server into a photos directory.

Do I have to request the photos property-by-property, or is there a better way? 
At the same time, I want to pull all property information.

For the code for pulling the photos from one property class (for ex. Residential), is it better to be placed inside the while loop when grabbing the information or is it better to be place outside of the while loop.

Snippet of my current code (it is somewhat working, but not properly):

	

     if($connect) {
           /*For one property class*/
	   $search = $rets->SearchQuery(
		'Property',								
		2,										
		'(105=2014-01-01+),(193=A)',	
		array(
			'Format'	=> 'COMPACT-DECODED',
			'Select'	=> '',
			'Count'		=> 1
		)
	);
	    
             $listings = array();

        if($rets->TotalRecordsFound() > 0) {
		while($data = $rets->FetchRow($search)) {
			array_push($listings, $data);

			$listing_id = $data['sysid'];
			$n = 1;
			//pulling all photos from this property class
			$photos = $rets->GetObject('Property', 'Photo', $listing_id);
			foreach($photos as $photo) {
				if ($photo['Success'] == true) {
					file_put_contents('photo/'.$listing_id.'-'.$n.'.jpg', $photo['Data']);
				}
				$n++;
			}
			$rets->FreeResult($photos);
		}
		echo "Collected  data successfully";
	} else {
		echo '0 Records Found';
	}
        
        /*for another property class.*/

	$search = $rets->SearchQuery(
		'Property',								
		13,									
		'(105=2013-01-01+),(193=A)',	
		array(
			'Format'	=> 'COMPACT-DECODED',
			'Select'	=> '',
			'Count'		=> 1
		)
	);

	$openhouses = array();
	$listings  = array();
	
	if($rets->TotalRecordsFound() > 0) {
		while($data = $rets->FetchRow($search)) {
			// Get open houses 
			if( $data[2360] != '' ){
			     array_push($openhouses, $data);
			}
			array_push($listings, $data);

                       //pulling all photos from this property class
                        $listing_id = $data['sysid'];
			$n = 1;
			$photos = $rets->GetObject('Property', 'Photo', $listing_id);
			foreach($photos as $photo) {
				if ($photo['Success'] == true) {
					file_put_contents('photo/'.$listing_id.'-'.$n.'.jpg', $photo['Data']);
				}
				$n++;
			}
			$rets->FreeResult($photos);	
		}
		echo "Collected All data successfully";
	} else {
		echo '0 Records Found';
	}

       /*There are 2 or 3 more sets of codes like that after one and another, however it is not updating properly nor pulling the update photos to the photo folder*/

        $rets->FreeResult($search);
	$rets->Disconnect();
        } else {
	     $error = $rets->Error();
	     print_r($error);
        }

What is the problem????

Thank you!

**Comment by troydavisson** [comment]
With `GetObject`, you can pass multiple IDs into the 3rd parameter (comma separated) to get multiple sets of objects back at once.
