### ISSUE TITLE
STANDARD-XML format, empty result

### ISSUE THREAD

**Issue by tampe125** [troydavisson/PHRETS#72]
I'm having some issues while trying to fetch the results from CREA (Canadian Real Estate Association) using the `STANDARD-XML` format.
First of all, I think their implementation is broken in so many ways: the date format is not the standard one, data fetched with `STANDARD-XML` format is different from the one fetched with the `COMPACT` one and so on.
Sadly I still have to integrate it.

After switching to the Standard format, the same query results in an empty collection. Digging inside the code, I saw that the XML parser is looking for the `DATA` attribute.
Sadly, this is not defined inside the XML, here it is a small snippet:

```xml
<RETS ReplyCode="0" ReplyText="Operation successful">
   <COUNT Records="1964"/>
   <RETS-RESPONSE>
   <Pagination>
      <TotalRecords>1964</TotalRecords>
      <Limit>100</Limit>
      <Offset>1</Offset>
      <TotalPages>20</TotalPages>
      <RecordsReturned>100</RecordsReturned>
   </Pagination>
   <PropertyDetails ID="14924275" LastUpdated="Sat, 18 Oct 2014 01:20:51 GMT">
        <ListingID>05131834</ListingID>
      .....
```

As far as I can tell, I think the response is broken (surprise surprise), do you think you can add an option to change the element used to wrap the entire recordset?

**Comment by troydavisson** [comment]
Version 2.0 doesn't yet have STANDARD-XML support as that's a pretty complex beast.  The ability to implement different parser strategies makes that a lot easier compared to 1.x, but the usage on STANDARD-XML is so small that it hasn't been a big priority for me.

You may want to look into their custom version of PHRETS which may get you closer to what you need:

https://github.com/tehraven/PHRetsForCREA/blob/master/PHRets_CREA.php
