### ISSUE TITLE
Memory Issues with searchQuery result

### ISSUE THREAD

**Issue by jwhulette** [troydavisson/PHRETS#75]
I was getting out of memory errors when processing 1000 or more records as the search query result set did not release the memory when I was done with it. I implanted the code found here, https://groups.google.com/forum/#!topic/phrets/vme4MWXEy9Q and it solved my issue completely. Each new query releases the the memory. I think this should be integrated into the next release.

**Comment by raygon3** [comment]
Troy, will this be fixed in the next release?

**Comment by TJonesy** [comment]
Any chance of this being fixed?

**Comment by troydavisson** [comment]
The `2.3` dev branch contains some changes which should help with this.  If you could try and version and report back with your findings on memory usage, I'd appreciate it.

**Comment by troydavisson** [comment]
Version 2.3 has been released and includes some changes which should address this.  Please give the latest version a try if able.
