### ISSUE TITLE
Guzzle 6.x on roadmap?

### ISSUE THREAD

**Issue by tomb10516** [troydavisson/PHRETS#76]
Hey folks!

I'm upgrading to Guzzle 6.x due to other dependencies in my project and I noticed that PHRETS doesn't yet support Guzzle 6.x.  Is Guzzle 6.x support on the roadmap for PHRETS?

Thanks!

**Comment by troydavisson** [comment]
I certainly imagine that we'll get there relatively soon.  The primary issue with this dependency currently is the recorder plugin we used which allows for "integration" testing without actually making requests.  I understand that a version of that which works with Guzzle 6.x is nearing release, and once that's done, I'll take version 6 for a spin and see what kind of project that update might be.

**Comment by tomb10516** [comment]
That would be awesome!

In the meantime I'll use a workaround by splitting off the data exchange in our codebase into a separate application sharing a local database with our main app.

Thanks for looking at the Guzzle 6.x thing!

**Comment by gsaulmon** [comment]
There is now a version of the recorder plugin for guzzle 6 that can be accessed here: https://github.com/gsaulmon/GuzzleRecorder/tree/guzzle-6

**Comment by tomb10516** [comment]
Thank you very much!
