### ISSUE TITLE
Retrieving information from a successful login

### ISSUE THREAD

**Issue by Lidbetter** [troydavisson/PHRETS#77]
During the login the parser gets information including: capabilities, details & valid_transactions. 

The details section of this login response gets thrown away (why?). I would like to be able to get the agent's id number from a successful login to more reliably determine which listing they own.

Could the details section be included in the bulletin object which is returned by the login method.

(I am logging into CREA rets.)

```
    $response = $this->request('Login');

    $parser = $this->grab('parser.login');
    $parser->parse($response->xml()->{'RETS-RESPONSE'}->__toString());

    foreach ($parser->getCapabilities() as $k => $v) {
        $this->capabilities->add($k, $v);
    }

    $bulletin = new Bulletin;
    // more code here
    return $bulletin;
```

**Comment by Lidbetter** [comment]
ping @troydavisson thoughts?

**Comment by troydavisson** [comment]
Not holding onto these and making them available was an oversight on my part.  About to push a change that lets you get these.

**Comment by troydavisson** [comment]
Thanks for bringing this to my attention!
