### ISSUE TITLE
Problem in downloading media files

### ISSUE THREAD

**Issue by bumse** [troydavisson/PHRETS#78]
I was not able to download photos from TREB (Toronto Real Estate Board) RETS server using PHRETS. The same search criteria worked with RETS connector Windows application. After monitoring HTTP traffic and comparing the two headers it turned out that some RETS servers like TREB require 'Accept' field to be present in header. By adding the field the problem got solved.

I'm suggesting we add `'Accept' => '*/*'` to Session constructor or allow for the field to be overridden by Configuration.

**Comment by troydavisson** [comment]
The `Accept` header is included by default by PHRETS now (as of Aug 10, 2015).
