### ISSUE TITLE
Not all field names returned when using StandardNames as an option in SearchQuery

### ISSUE THREAD

**Issue by andrewbriggs** [troydavisson/PHRETS#80]
I am following the example here: https://github.com/troydavisson/PHRETS/wiki/Connect,-download-listing-data-in-csv-format,-disconnect

When I use the SearchQuery option with StandardNames set to 1, the CSV does not return all field names. However, when using SystemNames, it does return all field names. I need to use StandardNames because they are more readable.

**Comment by troydavisson** [comment]
This is RETS working as designed.  If you use your credentials to log into www.retsmd.com and pull up one of the classes under the Property heading, the 2 left columns will be most important in this case.  When you aren't using StandardNames, you'll get the SystemName back (which all fields have).  When using StandardNames, you're only able to get back fields which also have a StandardName associated (column 2, probably much less populated).

This is intended behavior as part of the specification that all RETS servers implement against.  A new option was added in the most recent version of RETS but I'm not aware of any fully compliant RETS version 1.8 server at this point.
