### ISSUE TITLE
CURL Concurrency Issues

### ISSUE THREAD

**Issue by mikebronner** [troydavisson/PHRETS#81]
I am currently still using PHRETS 1 as it works for CRLMS (there are a few issues already opened on PHRETS 2 not working with CRMLS). Unfortunately it is causing concurrency issues with CURL requests hanging up the server (all available PHP instances are tied up).

Are there any async options available in PHRETS 1? Or perhaps any other work-around?

**Comment by troydavisson** [comment]
No, 1.x was built directly against curl using non-async options, and at this point, no further changes are planned for 1.x as I've shifted my resources towards version 2.
