### ISSUE TITLE
Guys, is there a way to get latitude & longitude?

### ISSUE THREAD

**Issue by alekseysavitsky** [troydavisson/PHRETS#83]

**Comment by mikebronner** [comment]
It depends on your RETS provider. Some have the fields, others don't. If they don't provide it, you will need to geocode the lat/long yourself using another service, like geocoder-php.

**Comment by alekseysavitsky** [comment]
Do you happen to know where shall I be looking for? Like what resource / class shall I call to check it?

**Comment by joselara** [comment]
It should be included with the property fields.

**Comment by mikebronner** [comment]
It really depends on your RETS provider. Use http://retsmd.com to inspect the resources and classes, otherwise you will have to refer to the documentation provided. Most likely it will be in the property resource.

**Comment by alekseysavitsky** [comment]
Thanks guys for the help, I did check everything but haven't found it. Hopefully it is something I can request from RETS provider.
