### ISSUE TITLE
Error Creating Tables: A table must have at least 1 column?

### ISSUE THREAD

**Issue by vartanian** [troydavisson/PHRETS#85]
I keep following your code for creating tables and am getting an error:
"CREATE TABLE rets_property_a ( PRIMARY KEY(` LIST_21`) )Error: CREATE TABLE rets_property_a ( PRIMARY KEY(` LIST_21`) )
A table must have at least 1 column"

Here is the code. What am I doing wrong?
<?php
require_once('login.php');
// gets resource information.  need this for the KeyField
$rets_resource_info = $rets->GetSystemMetadata()->getResources();

$resource = "Property";
$class = "A";
// or set through a loop

// pull field format information for this class
$rets_metadata = $rets->GetSystemMetadata($resource, $class);

$table_name = "rets_".strtolower($resource)."_".strtolower($class);
// i.e. rets_property_res

function create_table_sql_from_metadata($table_name, $rets_metadata, $key_field, $field_prefix = "") {
    $sql_query = "CREATE TABLE ".$table_name." (\n";
    foreach ($rets_metadata as $field) {
        $cleaned_comment = addslashes($field->getLongName());
        $sql_make = "\t`" . $field_prefix . $field->getSystemName()."` ";
        if ($field->getInterpretation() == "LookupMulti") {
            $sql_make .= "TEXT";
        } elseif ($field->getInterpretation() == "Lookup") {
            $sql_make .= "VARCHAR(50)";
        } elseif ($field->getDataType() == "Int" || $field->getDataType() == "Small" || $field->getDataType() == "Tiny") {
            $sql_make .= "INT(".$field->getMaximumLength().")";
        } elseif ($field->getDataType() == "Long") {
            $sql_make .= "BIGINT(".$field->getMaximumLength().")";
        } elseif ($field->getDataType() == "DateTime") {
            $sql_make .= "DATETIME default '0000-00-00 00:00:00' NOT NULL";
        } elseif ($field->getDataType() == "Character" && $field->getMaximumLength() <= 255) {
            $sql_make .= "VARCHAR(".$field->getMaximumLength().")";
        } elseif ($field->getDataType() == "Character" && $field->getMaximumLength() > 255) {
            $sql_make .= "TEXT";
        } elseif ($field->getDataType() == "Decimal") {
            $pre_point = ($field->getMaximumLength() - $field->getPrecision());
            $post_point = !empty($field->getPrecision()) ? $field->getPrecision() : 0;
            $sql_make .= "DECIMAL({$field->getMaximumLength()},{$post_point})";
        } elseif ($field->getDataType() == "Boolean") {
            $sql_make .= "CHAR(1)";
        } elseif ($field->getDataType() == "Date") {
            $sql_make .= "DATE default '0000-00-00' NOT NULL";
        } elseif ($field->getDataType() == "Time") {
            $sql_make .= "TIME default '00:00:00' NOT NULL";
        } else {
            $sql_make .= "VARCHAR(255)";
        }
        $sql_make .=  " COMMENT '".$cleaned_comment."',\n";
        $sql_query .= $sql_make;
    }
    $sql_query .=  "PRIMARY KEY(`".$field_prefix.$key_field."`) )";
    return $sql_query;
}

$sql = create_table_sql_from_metadata($table_name, $rets_metadata, "LIST_21");
print_r($sql);

if (mysqli_query($conn, $sql)) {
    echo "New record created successfully";
} else {
    echo "Error: " . $sql . "<br>" . mysqli_error($conn);
}

?>

**Comment by Aeyzaz** [comment]
Hi vartanian! Check your available classes at retsmd.com. There may be a Problem with your class name. Remember class name and Status are two seperate things.

**Comment by troydavisson** [comment]
I believe your `GetSystemMetadata` call needs to be using `GetTableMetadata` here instead in order to get field-level details for those fields.

**Comment by erobert17** [comment]
Troy was correct, I had to switch GetSystemMetadata with GetTableMetadata. Seems the old table creation example is out dated.

Here's my full working code for those who come after us.

`<?php
date_default_timezone_set('America/New_York');

require_once("vendor/autoload.php");


$rets_login_url = 'xxx';
$rets_username = 'xxx';
$rets_password = 'xxx';


$config = new \PHRETS\Configuration;
$config->setLoginUrl($rets_login_url)
        ->setUsername($rets_username)
        ->setPassword($rets_password)
        ->setRetsVersion('1.7.2');

$rets = new \PHRETS\Session($config);


$connect = $rets->Login();


$resource = "Property";
$class = "SF_1";
// or set through a loop

// pull field format information for this class
$rets_metadata = $rets->GetTableMetadata($resource, $class);


$table_name = "rets_".strtolower($resource)."_".strtolower($class);
//$table_name = 'rets';
// i.e. rets_property_res

$sql = create_table_sql_from_metadata($table_name, $rets_metadata, "L_ListingID");

$link = mysql_connect('localhost', 'root', 'password');
/*if (!$link) {
    die('Could not connect: ' . mysql_error());
}*/
echo 'Connected successfully';
mysql_select_db('upnorthProperties', $link);

$resultz = mysql_query($sql) or trigger_error(mysql_error()." in ".$sql);

//var_dump($resultz);


function create_table_sql_from_metadata($table_name, $rets_metadata, $key_field, $field_prefix = "") {
    $sql_query = "CREATE TABLE ".$table_name." (\n";
    foreach ($rets_metadata as $field) {
        $cleaned_comment = addslashes($field->getLongName());
        $sql_make = "\t`" . $field_prefix . $field->getSystemName()."` ";
        if ($field->getInterpretation() == "LookupMulti") {
            $sql_make .= "TEXT";
        } elseif ($field->getInterpretation() == "Lookup") {
            $sql_make .= "VARCHAR(50)";
        } elseif ($field->getDataType() == "Int" || $field->getDataType() == "Small" || $field->getDataType() == "Tiny") {
            $sql_make .= "INT(".$field->getMaximumLength().")";
        } elseif ($field->getDataType() == "Long") {
            $sql_make .= "BIGINT(".$field->getMaximumLength().")";
        } elseif ($field->getDataType() == "DateTime") {
            $sql_make .= "DATETIME default '0000-00-00 00:00:00' NOT NULL";
        } elseif ($field->getDataType() == "Character" && $field->getMaximumLength() <= 255) {
            $sql_make .= "VARCHAR(".$field->getMaximumLength().")";
        } elseif ($field->getDataType() == "Character" && $field->getMaximumLength() > 255) {
            $sql_make .= "TEXT";
        } elseif ($field->getDataType() == "Decimal") {
            $pre_point = ($field->getMaximumLength() - $field->getPrecision());
            $post_point = !empty($field->getPrecision()) ? $field->getPrecision() : 0;
            $sql_make .= "DECIMAL({$field->getMaximumLength()},{$post_point})";
        } elseif ($field->getDataType() == "Boolean") {
            $sql_make .= "CHAR(1)";
        } elseif ($field->getDataType() == "Date") {
            $sql_make .= "DATE default '0000-00-00' NOT NULL";
        } elseif ($field->getDataType() == "Time") {
            $sql_make .= "TIME default '00:00:00' NOT NULL";
        } else {
            $sql_make .= "VARCHAR(255)";
        }
        $sql_make .=  " COMMENT '".$cleaned_comment."',\n";
        $sql_query .= $sql_make;
    }
    $sql_query .=  "PRIMARY KEY(`".$field_prefix.$key_field."`) )";
    return $sql_query;
}`
