### ISSUE TITLE
PHRETS set time window for downloading images.

### ISSUE THREAD

**Issue by kunalhdoshi** [troydavisson/PHRETS#86]
I have to connect to the CREA server and download a large number of records. I have been successful in downloading all the fields separately. I have been trying to download images for the listings, but since the records are too many, they would take days at a time to download. Is there a way to get only a few records at a time by giving a LastUpdated time window or an offset of some sort. 

I have tried using the offset element in the optional params field, but it doesn't work. Is there some other method? If there is an option where LastUpdated can be used that would be best.

I am using PHRETS 1.7.2

**Comment by troydavisson** [comment]
The solution for this is generally outside of the scope of this library and probably more appropriate for the mailing list (https://groups.google.com/forum/#!forum/phrets).  To try and answer your question, though, there are a few ways this might be done.  2 quick ideas:

1. Find an appropriate field supported on the server which would represent this kind of Last Updated time and limit returned results based on that
2. Pull back a full list of ID + LastUpdated for all listings and then grab the full records for the ID's with LastUpdated values that don't match what you recorded the last time you did that request
