### ISSUE TITLE
how can i Handle ReplyCode and ReplayTex with Phrets 2

### ISSUE THREAD

**Issue by desaikalpesh34** [troydavisson/PHRETS#91]
Hey troy,
Thanks for amazing works....
I can't understand how can i handle ReplyCode and ReplayTex(means request to server is succeeded or fail ).

is there any built in method to handle this situation if yes then please Explain how can i handle.
i would like to over come this type of situation....

RETS ReplyCode="20206" ReplyText="Invalid Query Syntax. The syntax for the field: Approved does not match its search type.">
</RETS>

is there any suggestion....

**Comment by troydavisson** [comment]
It depends on which request you're making.  Based on the example you gave, an "Invalid Query Syntax" error would suggest a `Search()` call.  In those instances, PHRETS should throw an exception:

https://github.com/troydavisson/PHRETS/blob/master/src/Session.php#L373-L382

If that's **not** happening in some cases for you, I'd be interested in knowing about it.

**Comment by marek-mazur** [comment]
@desaikalpesh34 Do you know the solution for that?
```
query: '(Approved=1),(Status=|A)'
```
```
  Class: RESI
    Visible Name: Residential
    Description : Contains data for Residential searches.
    LookupTable: ESC[31mESC[47mApprovedESC[0m
      Resource: Property
      ShortName: ESC[31mESC[47mApprovedESC[0m
      LongName: Broker ESC[31mESC[47mApprovedESC[0m
      StandardName:
      Units:
      Searchable: 1
      Required: 0
      Types:
         ->
        FALSE -> 0
        TRUE -> 1
```
