### ISSUE TITLE
Use new version of guzzlehttp/guzzle 6.1.1 instead of guzzlehttp/guzzle: >=4.0,<6.0

### ISSUE THREAD

**Issue by ssnukala** [troydavisson/PHRETS#92]
I having issues with some other packages due to <6.0 for guzzlehttp/guzzle package.
Is there a way this package can be updated to use the new version of Guzzlehttp/guzzle.

I am not able to use other packages because of this dependency.

It would be great if phrets can be updated to use guzzlehttp/guzzle 6.1.1

**Comment by rappasoft** [comment]
+1

**Comment by ktwbc** [comment]
+1 This is starting to become more of an issue as more packages require the newer guzzlehttp

**Comment by troydavisson** [comment]
I'm still fighting with some tests that seem to be more of a problem with how the tests are working rather than the library, but I think I have this in pretty good shape overall.

In your `composer.json` file, change your requirement to:  `2.3.x-dev`

and let me know if you have any new issues with it.

**Comment by intrepidws** [comment]
If I need Guzzle 6.0+, do I still need to change my requirement to `2.3.x-dev`?

**Comment by troydavisson** [comment]
For now.  I plan to release 2.3 in the next few days.

**Comment by intrepidws** [comment]
Stupid GitHub newbie question, but will I be notified of a new release as long as I have this repo starred?

**Comment by troydavisson** [comment]
I'm not sure on that, but I'll close this issue with a comment, so you should at least be notified from that.

**Comment by troydavisson** [comment]
Version 2.3 has been released and includes Guzzle 6+ support.  Please give the latest version a try if able.

**Comment by intrepidws** [comment]
Works great so far. Thanks for all your work @troydavisson
