### ISSUE TITLE
Class 'Monolog\Logger' not found.

### ISSUE THREAD

**Issue by Aeyzaz** [troydavisson/PHRETS#93]
Hi, I've copied the sample code you provided in the Documentation but it shows 
Class 'Monolog\Logger' not found.

i have downloaded the package via composer and all the files are in vendor directory.

**Comment by troydavisson** [comment]
It's not clear exactly how you pulled all of that in with Composer, but PHRETS only uses Monolog as a dev dependency, so you'll need to either use that or include Monolog directly within your project's `composer.json` file.

**Comment by ahsan154** [comment]
i am getting same error, even i updated composer.json thrice

here how it is right now in my composer.json file

{
    "require": {
        "cakephp/debug_kit": "^3.2",
        "smalot/pdfparser": "*",
        "troydavisson/phrets": "2.*"
    }
}

**Comment by icarlosmendez** [comment]
ahsan154, 
Based on your comment above it would appear that your have not installed monolog yet.

If you haven't solved this issue you should go to the following url:
https://github.com/Seldaek/monolog

There you will find a line of code under the "Installation" heading that will use Composer to install Monolog. It will then be added to your composer.json file as well.

**Comment by ahsan154** [comment]
Yes you are correct and now i am getting the following error

( ! ) Fatal error: Uncaught exception 'PHRETS\Exceptions\RETSException' with message 'No Metadata Found' in D:\wamp\www\mls_fl\vendor\troydavisson\phrets\src\Session.php on line 379
( ! ) PHRETS\Exceptions\RETSException: No Metadata Found in D:\wamp\www\mls_fl\vendor\troydavisson\phrets\src\Session.php on line 379
