### ISSUE TITLE
CapabilityUnavailable

### ISSUE THREAD

**Issue by toadsteraz8** [troydavisson/PHRETS#94]
Having some issues using the application. It is telling me I need to possible run the Login however I have and can validate that it works (if I change the username or password I get an unauthorized error). 

### The response from the page is as follows:
Fatal error: Uncaught exception 'PHRETS\Exceptions\CapabilityUnavailable' with message ''GetMetadata' tried but no valid endpoint was found. Did you forget to Login()?' in /home/getarizonareales/public_html/RETS/src/Session.php:329 Stack trace: 
#0 /home/getarizonareales/public_html/RETS/src/Session.php(256): PHRETS\Session->request('GetMetadata', Array) 
#1 /home/getarizonareales/public_html/RETS/src/Session.php(169): PHRETS\Session->MakeMetadataRequest('METADATA-SYSTEM', 0, 'metadata.system')
#2 /home/getarizonareales/public_html/RETS/index.php(27): PHRETS\Session->GetSystemMetadata() 
#3 {main} thrown in /home/getarizonareales/public_html/RETS/src/Session.php on line 329

### My Log File looks like the Login works, it get a success 200 response as follows:
[2016-01-02 16:20:54] PHRETS.DEBUG: Loading Monolog\Logger logger [] []
[2016-01-02 16:20:54] PHRETS.DEBUG: Sending HTTP Request for http://retsgw.flexmls.com:6103/rets2_1/Login (Login) {"headers":{"User-Agent":"PHRETS/2.0","RETS-Version":"RETS/1.8","Accept-Encoding":"gzip","Accept":"*/*"},"cookies":[]} []
[2016-01-02 16:20:54] PHRETS.DEBUG: Response: HTTP 200 [] []

### My PHP code is as follows:
```
<?php

date_default_timezone_set('America/Phoenix');

require_once("vendor/autoload.php");

$log = new \Monolog\Logger('PHRETS');
//$log->pushHandler(new \Monolog\Handler\StreamHandler('php://stdout', \Monolog\Logger::DEBUG));
$log->pushHandler(new \Monolog\Handler\StreamHandler('app.log', \Monolog\Logger::DEBUG));

$config = new \PHRETS\Configuration;
$config->setLoginUrl('http://retsgw.flexmls.com:6103/rets2_1/Login')
        ->setUsername('HIDDEN')
        ->setPassword('HIDDEN')
		->setRetsVersion('1.8') // see constants from \PHRETS\Versions\RETSVersion
		->setHttpAuthenticationMethod('digest') // or 'basic' if required 
		->setOption('use_post_method', false) // boolean
		->setOption('disable_follow_location', false); // boolean

$rets = new \PHRETS\Session($config);
$rets->setLogger($log);

$connect = $rets->Login();

$system = $rets->GetSystemMetadata();
var_dump($system);
```

**Comment by troydavisson** [comment]
That RETS server doesn't support RETS 1.8.  If you change that `setRetsVersion()` line to `1.7.2` instead, you should have better luck.  If that still doesn't fix it, email me privately and I'll dig into that more.
