### ISSUE TITLE
Missing open parenthesis in subquery

### ISSUE THREAD

**Issue by jeffreyroberts** [troydavisson/PHRETS#97]
Using the following code is resulting in an error, specifying that the query is missing an opening parenthesis in the subquery....

    $results = $rets->Search('OpenHouse', '13', '*',     [
            'QueryType' => 'DMQL2',
            'Count' => 1, // count and records
            'Format' => 'COMPACT-DECODED',
            'Limit' => 99999999,
            'StandardNames' => 0, // give system names
        ]);

Here is the full error line

    [Mon Jan 18 20:49:30.411392 2016] [:error] [pid 4266] [client 208.93.204.249:35498] PHP Fatal error:  Uncaught exception 'PHRETS\\Exceptions\\RETSException' with message 'Missing open parenthesis in subquery. Reference ID: 9eeca13a-cfb9-4bff-8349-f5bfab5b0499' in /web/dev.PandaIDX.com/rets_example/vendor/troydavisson/phrets/src/Session.php:371\nStack trace:\n#0 /web/dev.PandaIDX.com/rets_example/vendor/troydavisson/phrets/src/Session.php(296): PHRETS\\Session->request('Search', Array)\n#1 /web/dev.PandaIDX.com/rets_example/index.php(47): PHRETS\\Session->Search('OpenHouse', '13', '*', Array)\n#2 {main}\n  thrown in /web/dev.PandaIDX.com/rets_example/vendor/troydavisson/phrets/src/Session.php on line 371

**Comment by bigoper** [comment]
Hey,

were you successful with it?

**Comment by troydavisson** [comment]
Using an asterisk as a DMQL query (or not providing a query at all) is only supported on a few RETS servers.  The server you're connected to does not appear to be one of those.

**Comment by troydavisson** [comment]
To elaborate a bit more, DMQL queries do typically require that conditions be surrounded with parentheses which is why that message is worded that way.  On the servers I've seen that support sending asterisks, the parentheses aren't required.

**Comment by llavillaccama** [comment]
Hi folks, please some idea because it shows me the following error:
I have :
 $results = $rets->Search(
    "Property",
    "RES",
    "*",
    [
        'QueryType' => 'DMQL2',
        'Count' => 1, 
        'Format' => 'COMPACT-DECODED',
        'Limit' => 10,
        'StandardNames' => 0, 
    ]
);

print_r($results);


Fatal error: Uncaught exception 'PHRETS\Exceptions\RETSException' with message 'Unauthorized Query' in ...\src\Session.php:361 Stack trace: #0 ...\src\Session.php(280): PHRETS\Session->request('Search', Array) #1 ...\index.php(60): PHRETS\Session->Search('Property', 'RES', '*', Array) #2 {main} thrown in ...\src\Session.php on line 361

**Comment by troydavisson** [comment]
@llavillaccama, see my last 2 comments on this issue.

**Comment by llavillaccama** [comment]
Thanks for your reply, after reviewing my code you can come to this conclusion and it works very well.

```
$results = $rets->Search('Property', 'Listing', '(Status=|ACT),(PropertyType=|RES)', ['Limit' => 1,'offset' => 10,'Select' => 'Address']);
echo "<pre>"; 
print_r($results->toArray());
echo "</pre>"; 
```

```
Array
(
    [0] => Array
        (
            [Address] => 35109 MCCULLOUGHS LEAP
        )

)
```


**I would like to know how I can get all the fields, I have tried putting**

'Select' => '*'
'Select' => '(*)'

And it has not worked for me.

Regards

**Comment by troydavisson** [comment]
Just don't include the `Select` option within that array at all.

**Comment by llavillaccama** [comment]
To remove the parameter gives me the following error

`$results = $rets->Search('Property', 'Listing', '(Status=|ACT),(PropertyType=|RES)', ['Limit' => 1,'offset' => 10]);`

` Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET .../?SearchType=Property&Class=Listing&Query=%28Status%3D%7CACT%29%2C%28PropertyType%3D%7CRES%29%2C~%28Address%3D%22%22%29&QueryType=DMQL2&Count=1&Format=COMPACT-DECODED&Limit=1&StandardNames=0&offset=10` resulted in a `404 Not Found` response' in ...\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 ...\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 ...\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 ...\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 ...\vendor\guzzlehttp\promises in ...\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113`


I do not know what is due but it seems that it is obligatory to pass the fields.

Thank you for your answers.

**Comment by troydavisson** [comment]
A 404?  That's special.  Not sure I understand the rationale for that.

OK, well I guess you'll need to either figure out the fields you want and specifically list them, or use `$rets->GetTableMetadata('Property', 'Listing')` to get the list of fields.

To do it automatically, you'd be looking at something (really ugly) like:

```php
$results = $rets->Search('Property', 'Listing', '(Status=|ACT),(PropertyType=|RES)', [
    'Limit' => 1,
    'Offset' => 10,
    'Select' => array_keys($rets->GetTableMetadata('Property', 'Listing')),
]);
```
