### ISSUE TITLE
/tmp directory filling up with php temporary files

### ISSUE THREAD

**Issue by smorocho** [troydavisson/PHRETS#98]
What would cause a RETS search to create files in /tmp?
I'm running a pretty large search dml query and the /tmp fille seems to fill up with a 50MB+ RETS response which seems to be the search results.  Anyhow these files end up filling up the /tmp folder and never getting cleaned out.
We connect to several RETS servers and (I think) this only seems to be happening with one server in particular.

**Comment by joselara** [comment]
You can use a program like tmpreaper that will clean up your /tmp folder. Other than that your tmp folder will be cleaned up when your server is restarted which is rare for a web server.

**Comment by troydavisson** [comment]
The only way the responses themselves should be persisted to a file is if you're using a debug mode parameter.  Outside of that, PHRETS does use temporary files to keep track of cookies throughout it's sessions, but these would be very small cookie-like files.

Without giving away credentials or anything, can you provide a portion of what one of those looks like?

**Comment by reedzhao** [comment]
I have the same issue. There are thousands of zero-byte `phrets*` files in `/tmp/`
![image](https://user-images.githubusercontent.com/16353524/47728807-7474f700-dc35-11e8-8695-6ff18a9d4167.png)

**Comment by quinncomendant** [comment]
I just found 9,510,187 empty phretsxxxxxx files in my /tmp directory. 😳

I guess PHPRETS doesn't do garbage collection? So I'll have to add a cron job to clear these out manually. 😖
